infrastructure/main.tf, infrastructure/variables.tf
- updated main.tf and variables.tf
=> FR-465- set up shared infra and vault

Jenkinsfile_CNP
=> fix the build

build.gradle, dependency-check-suppressions.xml, docker/app.yml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/pba/PaymentByAccount.java, src/test/functionalTest/java/uk/gov/hmcts/probate/functional/feelookuptests/FrFeeLookupTests.java
- fixed sonar issues
- updated docker-compose file
=> FR_463_implement_notifications_on_finrem_case_orchestration_service

README.md, docker/app.yml, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/smoketest/SmokeTest.java
- updated Docker-compose with notification service
=> Fr 381 docker compose notification service

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/NotificationServiceConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/NotificationServiceConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java, src/test/resources/application.properties
- initial draft implementation
=> FR-401_Consent_order_not_approved

dependency-check-suppressions.xml, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/e2etest/NotificationsTest.java
- Added dependancy suppression
- Added e2e test for notification end points
=> FR-588 Notification e2e test

Dockerfile, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/e2etest/NotificationsTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/insights/AppInsightsTest.java
=> Fix_Pmd_voilations

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/resources/fixtures/ccd-request-with-solicitor-email-consent.json, src/test/resources/fixtures/fee-lookup.json
- Added the new functionality
- updated the unit tests
=> FR_733_notification_emails_with_solicitor_consent

src/smokeTest/java/uk/gov/hmcts/reform/finrem/caseorchestration/smoketests/CaseOrchestrationSmokeTests.java, src/smokeTest/resources/application.properties
- removed hardcoded connection timeout values
=> FR_716_smoke_tests

src/functionalTests/resources/json/ccd-request-with-solicitor-assignedToJudge.json, src/functionalTests/resources/json/ccd-request-with-solicitor-consentOrderAvailable.json, src/functionalTests/resources/json/ccd-request-with-solicitor-consentOrderMade.json, src/functionalTests/resources/json/ccd-request-with-solicitor-consentOrderNotApproved.json, src/functionalTests/resources/json/ccd-request-with-solicitor-hwfSuccessfulEmail.json
=> Set dummy email for notication tests

dependency-check-suppressions.xml, docker/app.yml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceControllerTest.java, src/test/resources/fixtures/updatecase/amend-divorce-details-d81-individual.json, src/test/resources/fixtures/updatecase/amend-divorce-details-d81-joint.json, src/test/resources/fixtures/updatecase/amend-divorce-details-decree-absolute.json, src/test/resources/fixtures/updatecase/amend-divorce-details-decree-nisi.json, src/test/resources/fixtures/updatecase/amend-periodic-payment-order-without-agreement.json, src/test/resources/fixtures/updatecase/amend-periodic-payment-order.json, src/test/resources/fixtures/updatecase/amend-property-adjustment-details.json, src/test/resources/fixtures/updatecase/amend-remove-periodic-payment-order.json, src/test/resources/fixtures/updatecase/remove-property-adjustment-details.json, src/test/resources/fixtures/updatecase/remove-respondant-solicitor-details.json
https://tools.hmcts.net/jira/browse/FR-748
Amend Case details clean up callback implementation
```
[ ] Yes
[X ] No
```
=> Fr 748 amend case details

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OrderRefusalTranslator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OrderRefusalTranslatorTest.java, src/test/resources/fixtures/model/case-details-multiple-orders.json
https://tools.hmcts.net/jira/browse/FR-339
```
[ ] Yes
[ x] No
```
=> pick latest order for doc generation

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml, src/main/resources/bootstrap.yaml
=> Implement Helm Charts.

build.gradle, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/CaseOrchestrationApplication.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/client/DocumentClient.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/DocumentConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DraftOnlineDocumentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AbstractDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnlineFormDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RefusalOrderDocumentService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DraftOnlineDocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/AbstractDocumentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/DraftOnlineFormTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/GenerateMiniFormATest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnlineFormDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RefusalOrderDocumentServiceTest.java, src/test/resources/application.properties, src/test/resources/fixtures/contested/with-mini-form-A.json
https://tools.hmcts.net/jira/browse/FR-790
```
[ ] Yes
[ x] No
```
=> Contested online form

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/MiamCheckController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/MiamCheckService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BaseControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/MiamCheckControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/MiamCheckTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/MiamCheckServiceTest.java, src/test/resources/fixtures/contested/miam-attend-exempt.json, src/test/resources/fixtures/contested/miam-valid-attend-exempt.json
=> Miam check

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceControllerTest.java, src/test/resources/fixtures/contested/amend-divorce-details-decree-absolute.json, src/test/resources/fixtures/contested/amend-divorce-details-decree-nisi.json, src/test/resources/fixtures/contested/do-not-remove-checklists.json, src/test/resources/fixtures/contested/is-applicant-home-court.json, src/test/resources/fixtures/contested/remove-additional-property-details.json, src/test/resources/fixtures/contested/remove-complexity-details.json, src/test/resources/fixtures/contested/remove-domestic-violence-checklist.json, src/test/resources/fixtures/contested/remove-exceptions-when-applicant-attended-miam.json, src/test/resources/fixtures/contested/remove-other-checklist.json, src/test/resources/fixtures/contested/remove-other-reason-for-complexity.json, src/test/resources/fixtures/contested/remove-periodic-payment-order-details.json, src/test/resources/fixtures/contested/remove-previousMiamAttendance-checklist.json, src/test/resources/fixtures/contested/remove-property-adjustment-order-details.json, src/test/resources/fixtures/contested/remove-respondent-address-details.json, src/test/resources/fixtures/contested/remove-respondent-solicitor-details.json, src/test/resources/fixtures/contested/remove-urgency-checklist.json, src/test/resources/fixtures/contested/update-miam-exceptions-when-applicant-attended-family-mediator.json, src/test/resources/fixtures/contested/update-miam-exceptions-when-applicant-not-claiming-exemption.json, src/test/resources/fixtures/contested/update-periodic-payment-details-for-no-payment-for-children.json, src/test/resources/fixtures/contested/update-periodic-payment-details-with-benefits-for-children.json, src/test/resources/fixtures/contested/update-property-adjustment-order-details.json
- Solicitor is able to amend the application in drafted state.
https://tools.hmcts.net/jira/browse/FR-951
Solicitor is able to amend the application in drafted state.
```
[ ] Yes
[ X] No
```
=> FR-951 - Contested amend application

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceControllerTest.java
https://tools.hmcts.net/jira/browse/FR-966
Generate Draft Mini form when there is an amend application
```
[ ] Yes
[ X] No
```
=> Fr 966 amend application draft minform

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/client/PaymentClient.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FeeLookupController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ApplicationType.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FeeService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/SetUpUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DraftOnlineDocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FeeLookupControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/FeeLookUpTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/PBAPaymentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ApplicationTypeTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FeeServiceTest.java, src/test/resources/fixtures/contested/fee-lookup.json
=> Update to get the latest contested fee.

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java
- remove contested pba payment end point
https://tools.hmcts.net/jira/browse/FR-991
remove contested pba payment end point
```
[ ] Yes
[ x] No
```
=> FR_991_pdb-payment code cleanup

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BaseController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FeeLookupController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PaymentConfirmationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/PBAPaymentService.java, src/main/resources/application.properties, src/test/resources/application.properties
=> Fix the payment contested application description.

src/smokeTest/java/uk/gov/hmcts/reform/finrem/caseorchestration/smoketests/CaseOrchestrationSmokeTests.java, src/smokeTest/resources/application-saat.properties, src/smokeTest/resources/application.properties, src/smokeTest/resources/case.json
- fixed the smoke test to hit finrem-payment-service fee-lookup end point.
https://tools.hmcts.net/jira/browse/FR-1007
Fix smoke test on case orchestration
```
[ ] Yes
[ X] No
```
=> FR-1007_case_orchestration_smoke_test_fix

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/saat.tfvars, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/caseorchestration/ValidateHearingDatesTest.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ValidateHearingService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/HearingNonFastTrackDocumentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ValidateHearingServiceTest.java
=> FR-1027:Date of the hearing must be between 12 and 16 weeks

docker/app.yml
=> 1046: app repo upgrade

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/DocumentConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralLetterController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralLetterValidateController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/GeneralLetter.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/GeneralLetterData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnlineFormDocumentService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/SetUpUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralLetterControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralLetterValidateControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterServiceTest.java, src/test/resources/application.properties, src/test/resources/fixtures/general-letter.json, src/test/resources/fixtures/invalid-general-letter-body.json
https://tools.hmcts.net/jira/browse/FR-340
```
[ ] Yes
[x ] No
```
=> Fr 340 general letter

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/NotificationServiceConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java, src/test/resources/application.properties, src/test/resources/fixtures/contested/contested-hwf-without-solicitor-consent.json
contested hwf successful email notification integration
https://tools.hmcts.net/jira/browse/FR-899
contested hwf successful email notification integration
```
[ ] Yes
[X ] No
```
=> Fr 899 contested hwf successful

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
- fix the issue with email generation logic
https://tools.hmcts.net/jira/browse/FR-899
HWF email for contested cases
```
[ ] Yes
[ X] No
```
=> FR_899_contested_hwf_successful_email

README.md, bin/load-pba-reference-data.sh, bin/pba-service-token.sh, docker/app.yml, prd/Dockerfile, prd/init-db.sh
dockerise prd app in finrem case orchestration
script to load prd reference data
https://tools.hmcts.net/jira/browse/FR-1126
Add rd-professional-api to finrem-case-orchestration dockers.
```
[ ] Yes
[X ] No
```
=> Fr 1126 dockerise prd app in finrem case orchestration

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CurrentDateController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CurrentDateControllerTest.java
automatic date population in the UI
https://tools.hmcts.net/jira/browse/FR-1034
automatic date population in the UI
```
[ ] Yes
[ X] No
```
=> added controller to get current date

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/payments/PaymentServiceTests.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/error/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/error/NoSuchFieldExistsException.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ConsentedStatus.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AmendedConsentOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AmendedConsentOrderData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RespondToOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RespondToOrderData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/SetUpUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BaseControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/error/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AmendedConsentOrderDataTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AmendedConsentOrderTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RespondToOrderDataTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RespondToOrderTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderServiceTest.java, src/test/resources/fixtures/latestConsentedConsentOrder/amend-consent-order-by-caseworker.json, src/test/resources/fixtures/latestConsentedConsentOrder/amend-consent-order-by-solicitor.json, src/test/resources/fixtures/latestConsentedConsentOrder/draft-consent-order.json, src/test/resources/fixtures/latestConsentedConsentOrder/respond-to-order-solicitor.json
- implementation of latest consent order to be updated.
https://tools.hmcts.net/jira/browse/FR-1153
I can see the 'Latest Consent Order' under the copy of the draft consent order field
```
[ ] Yes
[X ] No
```
=> FR_1153_update_latest_consent_order

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintControllerTest.java
=> Creating send order event

build.gradle, src/functionalTests/resources/json/latestConsentedConsentOrder/amend-consent-order-by-caseworker.json, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/client/DocumentClient.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/PensionCollectionData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/PensionDocumentData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/document/DocumentValidationResponse.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AbstractDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DocumentValidationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/PensionCollectionDataTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/PensionDocumentDataTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/document/DocumentValidationResponseTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DocumentValidationServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnlineFormDocumentServiceTest.java, src/test/resources/fixtures/latestConsentedConsentOrder/CaseDocument.json, src/test/resources/fixtures/latestConsentedConsentOrder/respond-to-order-solicitor.json, src/test/resources/fixtures/latestConsentedConsentOrder/respond-to-order-without-consent-order.json, src/test/resources/fixtures/latestConsentedConsentOrder/validate-pension-collection-without-pension-data.json, src/test/resources/fixtures/latestConsentedConsentOrder/validate-pension-collection.json, src/test/resources/fixtures/pba-validate.json
implementation and unit tests of Consented File Upload Validation.
https://tools.hmcts.net/jira/browse/FR-1261
implementation and unit tests of Consented File Upload Validation.
```
[ ] Yes
[ X] No
```
=> Fr 1261_file_type_validation

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintControllerTest.java
=> rolling back update-latest-consent-order in bulk-print

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java, src/functionalTests/resources/application.properties
=> Bulk print functional tests new

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java, src/functionalTests/resources/application.properties, src/functionalTests/resources/json/consented/approved-consent-order.json
https://tools.hmcts.net/jira/browse/FR-1292
```
[x ] Yes
[ ] No
```
=> Added test for approved consent order

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintController.java
=> Adding logging

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintController.java
=> FR-862: fixing case state

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationController.java
Case state is not changing, hence fixed.
```
[ ] Yes
[X ] No
```
=> FR_1261_fix

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationController.java
- reverting case state fix
```
[ ] Yes
[X ] No
```
=> FR_1261_reverting_case_state_fix

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/DocumentValidationTests.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/util/FunctionalTestUtils.java, src/functionalTests/resources/application.properties, src/functionalTests/resources/json/consented/documentValidation/valiadate-draft-consent-order.json, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationController.java
- added functional test
```
[ ] Yes
[X] No
```
=> FR-1261_functional_tests

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationControllerTest.java, src/test/resources/fixtures/ccd-migrate-request.json
=> Update CCD Case data Migration.

src/functionalTests/resources/json/contested/generate-contested-form-A1.json, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentTranslator.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentTranslatorTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintServiceTest.java, src/test/resources/fixtures/bulk-print.json, src/test/resources/fixtures/contested/bulk_print_consent_order_approved.json, src/test/resources/fixtures/contested/bulk_print_consent_order_not_approved.json
=> FR-1217: Approve order for bulk print

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CheckLatestConsentOrderController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CheckLatestConsentOrderControllerTest.java, src/test/resources/fixtures/invalid-latest-consent-order.json, src/test/resources/fixtures/valid-latest-consent-order.json
https://tools.hmcts.net/jira/browse/FR-1159
```
[x] Yes
[ ] No
```
=> Fr 1159 check latest consent order

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/util/FunctionalTestUtils.java, src/functionalTests/resources/json/consented/bulk-print.json, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentTranslator.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CommonFunction.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentTranslatorTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintServiceTest.java, src/test/resources/fixtures/bulk-print-not-approved.json, src/test/resources/fixtures/bulk-print.json
=> Functional changes for bulk print

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/RejectedOrderDocumentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RefusalOrderDocumentService.java, src/smokeTest/java/uk/gov/hmcts/reform/finrem/caseorchestration/smoketests/CaseOrchestrationSmokeTests.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/SetUpUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/RejectedOrderDocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RefusalOrderDocumentServiceTest.java
Implemented Rest Endpoint To Preview the consent order not approved order
Implemented Rest Endpoint To Preview the consent order not approved order
```
[ ] Yes
[ X] No
```
=> Fr 1098 preview consent order not approved

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataControllerTest.java
=> Adding defaults for consented

bin/create-roles-users.sh, build.gradle, dependency-check-suppressions.xml, docker/app.yml, gradle/wrapper/gradle-wrapper.properties, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/DocumentValidationTests.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/util/FunctionalTestUtils.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BaseController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FeeLookupController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAValidateController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctions.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/MiamCheckService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ValidateHearingService.java
=> Updating the Beanutils dependency

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DocumentValidationService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java, src/test/resources/fixtures/contested/bulk_print_consent_order_approved.json, src/test/resources/fixtures/contested/bulk_print_consent_order_not_approved.json, src/test/resources/fixtures/contested/bulk_print_simple.json
=> Bulk print for applicant

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FinalOrderController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/HearingOrderCollectionData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/HearingOrderDocument.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FinalOrderControllerTest.java, src/test/resources/fixtures/final-order-for-stamping.json
=> FR-1341: send order

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderControllerTest.java
=> FR-1326 applicantRepresented fix

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FinalOrderController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinalOrderCollectionData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinalOrderDocument.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FinalOrderControllerTest.java, src/test/resources/fixtures/final-order-for-stamping-without-exsisting-order.json, src/test/resources/fixtures/final-order-for-stamping-without-hearing-order.json, src/test/resources/fixtures/final-order-for-stamping.json
=> FR-1341 making stamp doc collection

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataControllerTest.java, src/test/resources/fixtures/move-values-sample.json
=> adding move-collection method

build.gradle, dependency-check-suppressions.xml
=> Supressing vulnerabilities not able to fix

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationControllerTest.java, src/test/resources/fixtures/ccd-already-migrated-request.json
=> Migration for courts and judge allocated (Adding tests)

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java
=> Adding logs for traceability.

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java
=> Fixing judgeAllocated.

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java
=> Refactoring..

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DocumentValidationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DocumentValidationServiceTest.java, src/test/resources/fixtures/latestConsentedConsentOrder/validate-pension-collection-without-pension-data.json
https://tools.hmcts.net/jira/browse/FR-1402
```
[x] Yes
[ ] No
```
=> FR-1402 Removing mandatory pension documents code

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationControllerTest.java
=> Changes for new data structure for SL type

src/main/resources/markdown/consented-hwf-payment-confirmation.md, src/main/resources/markdown/consented-pba-payment-confirmation.md
https://tools.hmcts.net/jira/browse/FR-1365
```
[ ] Yes
[x] No
```
=> FR-1365 Update Court Address Information for consented journey

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
- implemented and added new tests
https://tools.hmcts.net/jira/browse/FR-1362
-email notification with FRCs
```
[ ] Yes
[ X] No
```
=> FR-1362-email notification with FRCs

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java, src/test/resources/fixtures/ccd-already-migrated-request.json, src/test/resources/fixtures/ccd-migrate-request_1.json, src/test/resources/fixtures/ccd-migrate-request_2.json, src/test/resources/fixtures/ccd-request-without-field.json
=> Migration fix for courts

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderControllerTest.java
=> Revert temporarily until migration is run

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/TransformationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/TransformationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/bulkscan/transformation/in/ExceptionRecord.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/bulkscan/transformation/output/CaseCreationDetails.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/bulkscan/transformation/output/SuccessfulTransformationResponse.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/TransformationControllerTest.java, src/test/resources/fixtures/model/exception-record.json
https://tools.hmcts.net/jira/browse/BSP-71
Creating a transformation endpoint in a new COS controller to
- pass incoming Exela JSON data to our service
- return the data transformed into a CCD case format
```
[ ] Yes
[x] No
```
=> BSP-71: Transformation Endpoint 

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ResponseExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/OcrValidationController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/OcrValidationControllerTest.java
Addresses checkstyle issues in BSP code causing master builds to fail.
```
[ ] Yes
[x] No
```
=> Hotfix: Checkstyle in BSP code

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/saat.tfvars, infrastructure/variables.tf, src/main/resources/application.properties
=> Adding missing service auth URL

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/DocumentValidationTests.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/payments/PaymentServiceTests.java
=> Ignoring tests for now

Jenkinsfile_CNP, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/DocumentValidationTests.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/payments/PaymentServiceTests.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/client/DocumentClient.java
=> Change DocumentClient to GET

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/OcrValidationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/TransformationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/UpdateController.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/TransformationControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/UpdateControllerTest.java, src/test/resources/application.properties
https://tools.hmcts.net/jira/browse/BSP-140
```
[ ] Yes
[ ] No
```
=> Securing rest of FR bulkscan endpoints

build.gradle, intellij-java-google-style.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkScanController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/event/bulkscan/BulkScanEvents.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkScanControllerTest.java
- Reintroduced event id for Create event
- It's not required for Update event
=> Reintroduced event id for create event.

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformations/FormAToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/validation/FormAValidatorTest.java
https://tools.hmcts.net/jira/browse/BSP-132
- form A validation class
- form A transformation class
- tests
```
[ ] Yes
[x] No
```
=> BSP-130: Form A section 2 validation and transformation

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/IntegrationTestBase.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/bulkscan/BulkScanIntegrationTest.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/caseorchestration/AmendCaseDetailsTest.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/idam/IdamUtils.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/util/FunctionalTestUtils.java, src/functionalTests/resources/application.properties, src/functionalTests/resources/json/bulkscan/basic.json
https://tools.hmcts.net/jira/browse/BSP-72
Integration tests
```
[ ] Yes
[x] No
```
=> BSP-72: integration tests

build.gradle, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/helper/BulkScanHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformations/FormAToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/helper/BulkScanHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/validation/FormAValidatorTest.java
https://tools.hmcts.net/jira/browse/BSP-131
- Validation and transformation for BSP-131 implemented - this consists of 5 non-mandatory fields, each composed of comma separated values
- Unit tests
```
[ ] Yes
[ ] No
```
=> BSP-131: FR Form A Section 3 Validation and Transformation

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/ApplicationConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkPrintController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentTranslator.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CommonFunction.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DocumentValidationService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetService.java, src/test/resources/fixtures/bulk-print.json
=> Fixing NPE when getting null value from casedata

Jenkinsfile_CNP, build.gradle, checkstyle.xml, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/TestContextConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CurrentDateController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DraftOnlineDocumentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FeeLookupController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/RemoveApplicantDetailsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/IdamService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ValidateHearingService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/NotificationsTest.java
=> Minor improvements after code review

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformations/FormAToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/OrderRefusalTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/validation/FormAValidatorTest.java
https://tools.hmcts.net/jira/browse/BSP-329
Section 2 and 3 fields are not added to FR exception record
```
[x] Yes
[ ] No
```
=> BSP-329: remove section 2 and 3

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/validation/FormAValidatorTest.java
https://tools.hmcts.net/jira/browse/BSP-333
Validation and transformation for FormA section 1.
```
[x] Yes
[ ] No
```
=> BSP-333: validation for section 1

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/validation/FormAValidatorTest.java
just updating label for fixed list
=> BSP-333: update label

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java
We're getting NullPointerExceptions for expected fields will empty values.
```
[ ] Yes
[ x ] No
```
=> Handling empty OCR values better

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/event/bulkscan/BulkScanEvents.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkScanControllerTest.java
Changing event name
```
[ ] Yes
[ x ] No
```
=> Changing event name

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkScanController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkScanControllerTest.java
Returning case type for FR consented
```
[ ] Yes
[ x ] No
```
=> Returning case type for FR consented

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/BSP-270
New field 'paperApplication' label: 'Was the application made on paper?', type=YesOrNo exists
=> BSP-270: paperApplication=Yes for BSP

build.gradle, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/OcrFieldName.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/validation/FormAValidatorTest.java
https://tools.hmcts.net/jira/browse/BSP-341
Children info
```
[ ] Yes
[x] No
```
=> BSP-341: section 1: details of App, validation & transformation - part 2

docker/app.yml, docker/test.yml
=> BSP-341: update docker config

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationController.java
Removing logging case ID as it can be null if documents are uploaded during initial application
=> Removed logging actual case ID as it may not always exist

build.gradle, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/TestContextConfiguration.java, src/functionalTests/resources/json/bulkscan/formA.json, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/helper/BulkScanHelper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/validation/FormAValidatorTest.java
https://tools.hmcts.net/jira/browse/BSP-373
```
[ ] Yes
[ ] No
```
=> Bump bsp-common version

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/bulkscan/CcdBulkScanIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/bulk/scan/domain/FormA.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/helper/BulkScanHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java
- Fixed typo and renamed 'applicantRepresent' to 'applicantRepresented'
- Set 'applicantRepresented' to Yes or No depending on value of 'applicantRepresentedPaper'
=> BSP-374: Additional transformation for applicant represented

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java
https://tools.hmcts.net/jira/browse/RPET-144
https://tools.hmcts.net/jira/browse/RPET-152
=> Amending case field

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java
=> BSP-389: Fixing typo on respondent's first and middle name field

infrastructure/main.tf
=> Adding missed variables in terraform

build.gradle, dependency-check-suppressions.xml
=> Suppressing vulnerabilities

Jenkinsfile_CNP
Reverts hmcts/finrem-case-orchestration-service#318
=> Revert "Reintroduce pipeline halt before production"

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/NotificationServiceConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FinalOrderController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FinalOrderControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java, src/test/resources/application.properties, src/test/resources/fixtures/final-order-for-stamping-without-email-consent.json
https://tools.hmcts.net/jira/browse/FR-1468
Call notification service on contest send order
```
[ ] Yes
[ ] No
```
=> Fr 1468 contest order notification

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderApprovedController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AbstractDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentServiceTest.java
=> Making AbstractDocumentService work with deep case data copy

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BaseController.java
Now checks for case type ID in case data
=> Extended conditions for isConsentedApplication 

charts/finrem-cos/Chart.yaml
=> update chart version

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/DocumentConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintServiceTest.java
- Fixed mismatch in Doc Configs (Replaced applicationAssignedToJudge... with assignedToJudgeNotification...)
- Added case ID to logs for better tracking
=> Fix mismatch in document config

Jenkinsfile_CNP, charts/finrem-cos/Chart.yaml, charts/finrem-cos/values.yaml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/NotificationServiceConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CommonFunction.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/NotificationServiceConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CommonFunctionTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java, src/test/resources/application.properties, src/test/resources/fixtures/applicant-solicitor-to-draft-order-with-email-consent.json, src/test/resources/fixtures/applicant-solicitor-to-draft-order-without-email-consent.json, src/test/resources/fixtures/respondent-solicitor-to-draft-order-with-email-consent.json
https://tools.hmcts.net/jira/browse/FR-1531
Adding new endpoint for triggering Solicitor to Draft Order email notification
```
[ ] Yes
[x] No
```
=> Implementing draft order email notification

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralLetterController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterServiceTest.java, src/test/resources/fixtures/general-letter-missing-address.json
https://tools.hmcts.net/jira/browse/FR-1595
- adding error message for missing address
```
[ ] Yes
[x] No
```
=> FR-1595 contested general letter

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationControllerTest.java, src/test/resources/fixtures/ccd-migrate-request-consented.json, src/test/resources/fixtures/ccd-migrate-request-invalid-court-data.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-london-ac.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-london.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-midlands-ac.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-midlands.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-northeast-ac.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-northeast.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-northwest-ac.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-northwest.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-southeast-ac.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-southeast.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-wales-ac.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-frc-wales.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-region-ac.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-invalid-region.json, src/test/resources/fixtures/ccd-migrate-request-no-court-data.json
https://tools.hmcts.net/jira/browse/FR-1543
update migration logic
```
[ ] Yes
[ ] No
```
=> update migration logic and defaults

build.gradle, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationControllerTest.java, src/test/resources/fixtures/ccd-migrate-request-invalid-court-data-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-birmingham-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-cfc-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-cleaveland-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-hsyorkshire-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-kent-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-liverpool-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-manchester-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-newport-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-nottingham-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-nwyorkshire-ga.json, src/test/resources/fixtures/ccd-migrate-request-migration-applicable-swansea-ga.json
=> handle ga fields

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetServiceTest.java, src/test/resources/fixtures/contested/general-letter-contested.json, src/test/resources/fixtures/general-letter-empty-collection.json, src/test/resources/fixtures/general-letter.json
https://tools.hmcts.net/jira/browse/FR-1724
Address line 3 should not be printed on documents as its pushing other data outside the letter window
=> FR-1724: Removed address line 3 from being printed on letters

.travis.yml, Dockerfile, build.gradle, gradle/wrapper/gradle-wrapper.properties
General Service Improvement
```
[ ] Yes
[x] No
```
=> Java 11 Upgrade

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CommonFunction.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CommonFunctionTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderServiceTest.java, src/test/resources/fixtures/general-order-consented-in-contested.json
https://tools.hmcts.net/jira/browse/FR-1582
=> FR-1582: Judge/Court Admin can trigger general order consent

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/DefaultsConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/MiniFormAController.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/DefaultsConfigurationTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/MiniFormAControllerTest.java, src/test/resources/application.properties
HOTFIX: move default Judge email to config to update prod
```
[ ] Yes
[ ] No
```
=> Default Judge email moved to config

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/idam/IdamUtils.java
adding retry to functional tests call for idam token
```
[ ] Yes
[x] No
```
=> adding retry to getting idam token

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/DocumentConfiguration.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ManualPaymentDocumentService.java, src/main/resources/application.properties, src/main/resources/json/court-details.json, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/TestSetUpUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ManualPaymentDocumentServiceTest.java, src/test/resources/application.properties, src/test/resources/fixtures/contested/paper-case-no-solicitors.json, src/test/resources/fixtures/contested/paper-case.json
https://tools.hmcts.net/jira/browse/FR-1507
Implementing Manual Payment Letter for Contested Paper Cases
```
[ ] Yes
[x] No
```
=> FR 1507: Manual Payment Letter (Contested Paper Cases)

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ManualPaymentDocumentService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ManualPaymentDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/FR-1507
Removing respondent notification letter for manual payment
```
[ ] Yes
[x] No
```
=> Removing respondent notification letter for manual payment

build.gradle, dependency-check-suppressions.xml
**Addressing Vulnerabilities:**
https://nvd.nist.gov/vuln/detail/CVE-2020-10663
https://nvd.nist.gov/vuln/detail/CVE-2020-7712
```
[ ] Yes
[x] No
```
=> Bump OWASP DependencyCheck

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/RejectedOrderDocumentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ConsentOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/OrderRefusal.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OrderRefusalTranslatorService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RefusalOrderDocumentService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/TestSetUpUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/RejectedOrderDocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/RejectionOrderTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/OrderRefusalTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OrderRefusalTranslatorServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OrderRefusalTranslatorTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RefusalOrderDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/RDM-10001
```
[ ] Yes
[ ] No
```
=> Hotfix judge not approved

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java
https://tools.hmcts.net/jira/browse/FR-1873
Email Respondent Solicitor - Solicitor to Draft Order
```
[ ] Yes
[ ] No
```
=> FR-1873: Email Respondent Solicitor - Solicitor to Draft Order

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java
=> remove org name after deprecation

dependency-check-suppressions.xml
=> supressing junit

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseDataService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedCaseOrderService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RestService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedCaseOrderServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnlineFormDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/FR-1938
Remove next hearing doc from print pack when not required
```
[ ] Yes
[ ] No
```
=> FR-1938: Remove next hearing doc from print back

build.gradle
=> upgrade guava

charts/finrem-cos/values.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ContestedDraftOrderNotApprovedController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ContestedOrderController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/Features.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedCaseOrderService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FeatureToggleService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ContestedDraftOrderNotApprovedControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ContestedOrderControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FeatureToggleServiceTest.java, src/test/resources/application.properties
https://tools.hmcts.net/jira/browse/FR-1925
```
[ ] Yes
[x] No
```
=> FR-1925: Removing offline notifications feature flags

build.gradle, dependency-check-suppressions.xml, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/payments/PaymentServiceTests.java, src/functionalTests/resources/application.properties, src/functionalTests/resources/json/contested/SuccessPaymentRequestPayload_Contested.json
- un-ignored payments tests and removed `Thread.sleep`
- fixed vulnerabilities
```
[ ] Yes
[x] No
```
=> Un-ignoring tests and fixing vulnerabilities

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PaymentConfirmationController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PaymentConfirmationControllerTest.java
=> Enable ACA API call to enable SaC

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderApprovedController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentService.java
[RPET-707](https://tools.hmcts.net/jira/browse/RPET-707)
[INC5144252](https://mojcppprod.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3D4c0393d3db8de8109fce470505961995%26sysparm_stack%3D%26sysparm_view%3D)
Introduce context with logging to aid with looking into production incident.
```
[ ] Yes
[X] No
```
=> Add context to log statements around approve consent order

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FeatureToggleService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FeatureToggleServiceTest.java
- Serialisation of JSON for UploadedCaseDocuments for caseDocumentConfidential is now behind RespondentSolicitorJourney toggle
=> Prod INC5158205 fix

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UpdateSolicitorDetailsService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UpdateSolicitorDetailsServiceTest.java
https://tools.hmcts.net/jira/browse/FR-1932
Pre-populate applicant organisation details
```
[ ] Yes
[ ] No
```
=> FR-1932: Pre-populate applicant organisation details

charts/finrem-cos/values.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/AddUserRolesRequestMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/AddUserRolesRequest.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/CaseAssignedUserRoleWithOrganisation.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdDataStoreService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/TestConstants.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/AddUserRolesRequestMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdDataStoreServiceTest.java
=> Re assign creator role

charts/finrem-cos/Chart.yaml, charts/finrem-cos/requirements.yaml
https://tools.hmcts.net/jira/browse/FR-1981
Upgrades Helm chart to v2
```
[ ] Yes
[x] No
```
=> Upgrade Helm chart API version to v2

build.gradle, charts/finrem-cos/Chart.yaml, src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/FR-1984
Updates base chart to latest version
```
[ ] Yes
[x] No
```
=> Update base chart to latest version

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ContestedDraftOrderNotApprovedController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseDataService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderNotApprovedDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderPrintService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedCaseOrderService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HelpWithFeesDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ManualPaymentDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/PaperNotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ContestedDraftOrderNotApprovedControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedCaseOrderServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HelpWithFeesDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ManualPaymentDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OrderRefusalTranslatorServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/PaperNotificationServiceTest.java, src/test/resources/fixtures/consented-ccd-request-with-solicitor-agreed-to-emails.json
https://tools.hmcts.net/jira/browse/FR-1702
- introduced PaperNotificationService and moved logic related to printed notifications there from NotificationsController
- added printing notifications to respondent solicitor
```
[ ] Yes
[x] No
```
=> FR-1702 respondent email preferences

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ContestedUploadedDocument.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FeatureToggleService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UploadContestedCaseDocumentsService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FeatureToggleServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UploadContestedCaseDocumentsServiceTest.java
https://tools.hmcts.net/jira/browse/FR-1963
- Re-created all collections to reflect document display (10 for each Applicant and Respondent) 
- Created filters for all collections
```
[ ] Yes
[ ] No
```
=> FR-1963 Amend document display in Contested

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentControllerTest.java
https://tools.hmcts.net/jira/browse/RPET-883
- improved error message passed to UI to include details why case couldn't be assigned to organisation
```
[ ] Yes
[x] No
```
=> RPET-883: improve error message

charts/finrem-cos/Chart.yaml
Upgrading to latest version of [chart-java (3.4.5)](https://github.com/hmcts/chart-java/releases/tag/v3.4.5)
Fixes # (issue)
https://tools.hmcts.net/jira/browse/RPET-921
platform operations upgrade
=> RPET-921 chart java bump

src/main/resources/json/court-details.json, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/RPET-940
- Update newcastle court address from:
`The Law Courts, The Quayside, Newcastle-upon-Tyne, NE1 3LA`
to `Barras Bridge, Newcastle upon Tyne, NE18QF`
```
[ ] Yes
[x] No
```
=> RPET-940: Update newcastle court address

charts/finrem-cos/values.preview.template.yaml
I'm not sure why, but I can see in FR there is some additional magic.
https://github.com/hmcts/finrem-case-orchestration-service/pull/567
=> Apparently it must be false on preview

build.gradle
=> DFR-76: Upgrade Spring Boot to 2.3.11.RELEASE

build.gradle
- [ x] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/DFR-114
To fix the nightly build .
```
[ ] Yes
[ x] No
```
=> DFR-114 Disable DotNet dependency checks

Jenkinsfile_nightly, build.gradle, charts/finrem-cos/Chart.yaml, config/fortify-client.properties, security.sh
DFR-471
Fortify setup in nightly build
```
[ ] Yes
[ x] No
```
=> DFR-471: Fortify Setup

audit.json
DFR-471
Add false positives for sec scan
```
[ ] Yes
[ x] No
```
=> DFR-471: Add false positives for sec scan

Jenkinsfile_CNP, build.gradle
https://tools.hmcts.net/jira/browse/DFR-682
enable pact on PR and restore contract test sourceset
```
[ ] Yes
[x] No
```
=> enable pact test on PR

build.gradle
DFR-682
revert sourceSet change as intellij do not recogise as a source folder (smoke, functional and contract)
This is due to name of task.
```
[ ] Yes
[ x] No
```
=> revert sourceSet change

build.gradle
=> DFR-715: upgrade log4j

build.gradle
=> DFR-729-log4-upgrade-2-16

build.gradle
na
removed jenter in bspcommon lib
```
[ ] Yes
[x] No
```
=> removed jenter in bspcommon lib

build.gradle, charts/finrem-cos/Chart.yaml
DFR-880: update java chart verison
=> DFR-880: update java chart verison

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java
DFR 767 
civil partnership flag
```
[ ] Yes
[x] No
```
=> DFR 767 civil partnership

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralApplicationController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenericDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralApplicationControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-589
=> DFR-589 convert word documents to PDFs

charts/finrem-cos/Chart.yaml
=> bump chart

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/UploadContestedCaseDocumentController.java
https://tools.hmcts.net/jira/browse/DFR-866
=> DFR-866 Add log

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataControllerTest.java
=> increase test coverage

charts/finrem-cos/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1140
```
[ ] Yes
[ ] No
```
=> Java chart Update Chart.yaml

audit.json
=> fix nightly security scan issue

security.sh
=> DFR-927: fix nightly security scan issue

build.gradle, charts/finrem-cos/Chart.yaml
=> Adding jackson versions and bumping chart.yaml java version

build.gradle, dependency-check-suppressions.xml
=> Bump springframework dependencies

charts/finrem-cos/Chart.yaml, charts/finrem-cos/values.yaml, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSSE-1394
```
[ ] Yes
[ ] No
```
=> Add Autoscaling finrem-cos Update Chart.yaml

charts/finrem-cos/Chart.yaml, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSSE-1264
```
[ ] Yes
[ ] No
```
=> repo mod Update Chart.yaml

audit.json
https://tools.hmcts.net/jira/browse/DFR-1013
FIx-security scan issue - causing pipeline to fail
```
[ ] Yes
[x] No
```
=> DFR-1013: fix security scan issue

audit.json
N/A
Fix security scan issue - added fingerprint url in audit.json
```
[ ] Yes
[x] No
```
=> fix security scan issue

audit.json
fix security scan issue on nightly pipeline.
=> fix: security scan issue

src/main/resources/bootstrap.yaml
[DFR-1072](https://tools.hmcts.net/jira/browse/DFR-1072)
```
[ ] Yes
[ x] No
```
=> DFR-1072: Fix issue with NoC secrets

charts/finrem-cos/Chart.yaml, charts/finrem-cos/values.yaml
[DFR-1072](https://tools.hmcts.net/jira/browse/DFR-1072)
```
[ ] Yes
[x ] No
```
=> DFR-1072: Add NoC secrets to Charts

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/letters/handler/AbstractLetterHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/letters/handler/litigant/applicant/SolicitorChangedApplicantLetterHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/letters/handler/litigant/respondent/SolicitorChangedRespondentLetterHandler.java, src/test/resources/fixtures/noticeOfChange/consented/add-respondent-solicitor-with-sol-address-and-no-email-before.json, src/test/resources/fixtures/noticeOfChange/consented/remove-respondent-solicitor-with-sol-address-and-no-email.json, src/test/resources/fixtures/noticeOfChange/contested/noc/add-with-solicitor-and-applicant-addresses-and-no-emails-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-add-and-revoke-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-add-and-revoke.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-add-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-add.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-max-cor-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-max-cor.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-no-solicitor-email-applicant-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-no-solicitor-email-applicant.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-no-solicitor-email-no-applicant-address-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-no-solicitor-email-no-applicant-address.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-revoke-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/noc-letter-notifications-revoke.json, src/test/resources/fixtures/noticeOfChange/contested/noc/remove-with-no-solicitor-address-and-with-applicant-addresses-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/remove-with-solicitor-and-applicant-addresses-and-no-emails-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/remove-with-solicitor-and-applicant-addresses-and-no-emails.json, src/test/resources/fixtures/noticeOfChange/contested/noc/remove-with-solicitor-and-applicant-emails-before.json, src/test/resources/fixtures/noticeOfChange/contested/noc/remove-with-solicitor-and-applicant-emails.json
[DFR-1067](https://tools.hmcts.net/jira/browse/DFR-1067)
```
[ ] Yes
[x ] No
```
=> DFR-1067: Fix issue with sending letters with empty address details

src/cftlib/java/uk/gov/hmcts/reform/finrem/caseorchestration/CftLibConfig.java
A new role was added to FinRem and that needs to be reflected in our local environment setup by adding it to the rse-cft-lib plugin config
=> Fix bootWithCCD task by adding new role

audit.json, build.gradle
=> Bumping tomcat and suppressing security scan issue

audit.json
https://tools.hmcts.net/jira/browse/DFR-1113
fix security scan failure
```
[ ] Yes
[x] No
```
=> DFR-1113: fix security scan failure

audit.json
=> Adding two suppressions

src/cftlib/java/uk/gov/hmcts/reform/finrem/caseorchestration/CftLibConfig.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/NotificationRequestMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/notification/NotificationRequest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/notification/NotificationRequestTest.java
https://tools.hmcts.net/jira/browse/DFR-1121
Add phone hours dynamically to email notifications via extra field in notification request
```
[ ] Yes
[x] No
```
=> DFR-1121 - Add phone opening hours to email notification request

dependency-check-suppressions.xml
[DFR-1172](https://tools.hmcts.net/jira/browse/DFR-1172)
Suppress log4j vulnerability
```
[ ] Yes
[ x] No
```
=> DFR-1172: Suppress log4j vulnerability

audit.json
https://tools.hmcts.net/jira/browse/DFR-1175
fix security scan issue
```
[ ] Yes
[x] No
```
=> DFR-1175: fix security scan issue

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DFR-1204
```
[ ] Yes
[x ] No
```
=> DFR-1204: Suppress Ripudaman vulnerability (false positive)

charts/finrem-cos/Chart.yaml
https://tools.hmcts.net/jira/browse/DFR-1211
updated java chart version
```
[ ] Yes
[x] No
```
=> DFR-1211: updated java chart version

charts/finrem-cos/Chart.yaml, dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderApprovedController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/InterimHearingService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderApprovedControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/HearingFastTrackDocumentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/InterimHearingServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-717
=> Dfr 717 rewind

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/InterimHearingService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/InterimHearingServiceTest.java
DFR-1232
Interim hearings notices blank
```
[x] Yes
[ ] No
```
=> DFR-1232: Interim hearings notices blank

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DocumentValidationControllerTest.java, src/test/resources/fixtures/latestConsentedConsentOrder/amend-consent-order-by-solicitor-contested.json
DFR-1066
exclude contested callback from consent callback
```
[ ] Yes
[x] No
```
=> DFR-1066: exclude contested callback from consent callback

src/functionalTests/resources/application.properties
https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1660039539747829
Functional test 404 fix
```
[ ] Yes
[x] No
```
=> fix functional test 404

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidatorTest.java
https://tools.hmcts.net/jira/browse/DFR-1155
Consent order-Allow Nullity\Judicial separation case number
```
[ ] Yes
[x] No
```
=> DFR-1155: Consent order-Allow Nullity\Judicial separation case number

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
Resolves: https://tools.hmcts.net/jira/browse/DFR-636
=> Remove notification for application issued for respondent

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/InterimHearingService.java
adding more logs in interim hearing service to find logs in azure
=> adding more logs in interim hearing service to find logs in azure

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UploadApprovedOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UploadApprovedOrderServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-1296
```
[ ] Yes
[X ] No
```
=> Dfr 1296 fr contested prevent orders being duplicated

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/ConsentedCourtHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/ContestedCourtHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/resources/json/court-details.json, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/helper/ConsentedCourtHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/helper/ContestedCourtHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctionsTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ManualPaymentDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-1292
=> dfr1292 updated FRC details and added 2 new

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/InterimHearingService.java
DFR-1294
Interim hearing notices to include time estimate
```
[ ] Yes
[x] No
```
=> DFR-1294: Interim hearing notices to include time estimate

config/owasp/suppressions.xml
=> fix cve error

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelper.java
Fix status
```
[ ] Yes
[ ] No
```
=> fix ga outcome status

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/NotificationRequestMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/notification/NotificationRequest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/BaseServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/NotificationRequestMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/notification/NotificationRequestTest.java
DFR-120
add party names in notification
```
[ ] Yes
[x] No
```
=> DFR-120: add party names in notification

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseDataService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetServiceTest.java, src/test/resources/fixtures/bulkprint/bulk-print-empty-solicitor-address-and-empty-postcode.json
https://tools.hmcts.net/jira/browse/DFR-1238
remove postcode validation for consent order approval
```
[ ] Yes
[x] No
```
=> DFR-1238 - remove postcode validation for consent order approval

build.gradle
=> bump snakeyaml to v.1.33

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/EventType.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedAboutToStartHandlerTest.java
DFR-1142
added additional doc upload option
```
[ ] Yes
[x] No
```
=> DFR-1142: added additional doc upload option

config/owasp/suppressions.xml
=> Suppressing jackson databind

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationOutcomeAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationOutcomeAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationReferToJudgeAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationReferToJudgeAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/RejectGeneralApplicationAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationOutcomeAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationOutcomeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationReferToJudgeAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationReferToJudgeAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/RejectGeneralApplicationAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/RejectGeneralApplicationAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationServiceTest.java
DFR-1371
General Application PDF conversion migration
```
[ ] Yes
[x] No
```
=> DFR-1371 General Application PDF conversion migration

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenericDocumentService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenericDocumentServiceTest.java
Reverts hmcts/finrem-case-orchestration-service#817
=> Revert "DFR-1322 Amended miniFormTemplate=FL-FRM-APP-ENG-00002.docx with suffix DE…"

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ContestedOrderController.java
=> fortify-patch

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/document/BulkPrintDocument.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/HearingFastTrackDocumentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/HearingNonFastTrackDocumentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsServiceTest.java
Dfr 1384
log filename for bulk print
```
[ ] Yes
[ ] No
```
=> Dfr 1384 log filename for bulk print

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/IssueApplicationConsentedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/IssueApplicationContestedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/EventType.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnStartDefaultValueService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/IssueApplicationConsentedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/IssueApplicationContestedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnStartDefaultValueServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-1425
Contested - Issue date should be pre-populated
```
[ ] Yes
[x] No
```
=> DFR-1425: Contested - Issue date should be pre-populated

config/owasp/suppressions.xml
=> supress spring web

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/NotificationRequestMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/NotificationRequestMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
[DFR-1385: ](https://tools.hmcts.net/jira/browse/DFR-1385)
Fix general email
```
[ ] Yes
[x] No
```
=> DFR-1385: general email

build.gradle, config/owasp/suppressions.xml
NA
Fix dependencies
```
[ ] Yes
[x] No
```
=> Fix dependencies

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentControllerTest.java
https://tools.hmcts.net/jira/browse/DFR-1442
List for hearing - addition doc
```
[ ] Yes
[x] No
```
=> DFR-1442: List for hearing - addition doc

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentServiceTest.java, src/test/resources/fixtures/contested/hearing-with-case-details-before.json
DFR-1366
additional document pdf conversion
```
[ ] Yes
[x] No
```
=> DFR-1366: additional document pdf conversion

config/owasp/suppressions.xml
=> Removing unused suppressions

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/RejectGeneralApplicationAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/RejectGeneralApplicationAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/DFR-1462
change-end-state-reject-general-application
```
[ ] Yes
[x] No
```
=> DFR-1462: change-end-state-reject-general-application

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctions.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentHearingService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctionsTest.java
DFR-1530
FR Consented - List for hearing - error of fetchin
```
[ ] Yes
[x] No
```
=> DFR-1530: FR Consented - List for hearing - error of fetching court fix

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctions.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctionsTest.java
DFR-1568
court issue fix
```
[ ] Yes
[x] No
```
=> DFR-1568: court issue fix

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ClevelandCourt.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RegionLondonFrc.java
[DFR-1622](https://tools.hmcts.net/jira/browse/DFR-1622)
```
[ ] Yes
[ ] No
```
=> DFR-1622: Courts issue fixed

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/DFR-1625
see ticket
```
[ ] Yes
[x] No
```
=> DFR-1625: update deprecated callback

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/barristers/BarristerRepresentationChecker.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/barristers/BarristerRepresentationCheckerTest.java
[DFR-1627](https://tools.hmcts.net/jira/browse/DFR-1627)
```
[ ] Yes
[ ] No
```
=> DFR-1627: Add null check to BarristerRepresentationChecker

build.gradle, config/owasp/suppressions.xml
=> fix dependency check

build.gradle
=> Reduce the mutation threshold to 75

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/NatureApplication.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedAboutToStartHandlerTest.java
Reverts hmcts/finrem-case-orchestration-service#882
=> Revert "DFR-1590: FR_addSchedulingListingInfo refector handler to use pojo"

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ConsentApplicationApprovedInContestedAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ConsentApplicationApprovedInContestedAboutToStartHandlerTest.java
Reverts hmcts/finrem-case-orchestration-service#872
=> Revert "DFR-1600: Consent Application Approved"

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/ContestedCourtHelper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/helper/ContestedCourtHelperTest.java
DFR-1715
List for hearing north east court
```
[ ] Yes
[x] No
```
=> DFR-1715: List for hearing north east court

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/UploadGeneralDocumentType.java
DFR-1723
FR Contested UploadGeneralDocumentType enum
```
[ ] Yes
[x] No
```
=> DFR-1723: FR Contested UploadGeneralDocumentType enum

config/owasp/suppressions.xml
=> Suppressing bad CVE

build.gradle, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ChildRelation.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/BarristerCollectionItem.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ChildDetails.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ChildDetailsCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ChildDetailsCollectionElement.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/GeneralOrderCollectionItem.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/GeneralOrderWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/ScheduleOneWrapper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/FinremCaseDetailMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/CCDConfigValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/FinremCaseDataTest.java
DFR-1589:
children collection pojo
```
[ ] Yes
[x] No
```
=> DFR-1589: children collection pojo

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataControllerTest.java
- [ X] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/DFR-1396
```
[ ] Yes
[x ] No
```
=> DFR-1396: Modified promptForUrgentCaseQuestion line to test

charts/finrem-cos/Chart.yaml
DFR-1758
update-chart-version
```
[ ] Yes
[x] No
```
=> DFR-1758: update-chart-version

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/State.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/CCDConfigValidator.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/FinremCaseDataTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/StateAttributes.java
[DFR-1779](https://tools.hmcts.net/jira/browse/DFR-1779)
Validate State model against spreadsheet
```
[ ] Yes
[x ] No
```
=> DFR-1779: Validate State model against spreadsheet

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/GeneralApplicationWrapper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/CCDConfigValidator.java
DFR-1781
Add dynamic list to model
```
[ ] Yes
[ x] No
```
=> DFR-1781: Add DynamicList to Model

charts/finrem-cos/Chart.yaml
[DFR-1783](https://tools.hmcts.net/jira/browse/DFR-1783)
Update java charts
```
[ ] Yes
[ x] No
```
=> DFR-1783: Update java charts

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ApprovedConsentOrderSubmittedHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ApprovedConsentOrderSubmittedHandlerTest.java
[DFR-1764](https://tools.hmcts.net/jira/browse/DFR-1764)
Disable CSTC email for Consent Order Available
```
[ ] Yes
[ x] No
```
=> DFR-1764: Disable CSTC email for Consent Order Available

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/DocumentValidationTests.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AmendedConsentOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/Court.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RespondToOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DefaultCourtListWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/InterimCourtListWrapper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/FinremCaseDetailMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AmendedConsentOrderDataTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AmendedConsentOrderTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RespondToOrderDataTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/RespondToOrderTest.java
DFR-1782
fix amendedConsentOrderDate in amend consent order
```
[ ] Yes
[x] No
```
=> DFR-1782: fix amendedConsentOrderDate in amend consent order

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/notification/NotificationTests.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/correspondence/assigntojudge/AssignToJudgeCorresponder.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/NotificationsTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/noc/NocLettersNotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/noc/NocTestConfig.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/correspondence/assigntojudge/AssignToJudgeCorresponderTest.java, src/test/resources/fixtures/consented-ccd-request-with-solicitor-agreed-to-emails.json
DFR-1674
Refactor of assign to judge correspondence
```
[ ] Yes
[x ] No
```
=> DFR-1674: Assign to judge refactor correspondence

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UploadContestedCaseDocumentsAboutToSubmitHandler.java
[DFR-1795](https://tools.hmcts.net/jira/browse/DFR-1795)
Fix confidential docs issue
```
[ ] Yes
[x ] No
```
=> DFR-1795: Fix confidential docs issue

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/ContestedCourtHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/helper/ContestedCourtHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctionsTest.java
=> DFR-1791: Contested - on Upload order event drop down is not working

build.gradle
=> Upgrade owasp version

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderServiceTest.java
DFR-1669
fr court details in letter
```
[ ] Yes
[x] No
```
=> DFR-1669: fr court details in letter

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/ContestedGeneralOrder.java
https://tools.hmcts.net/jira/browse/DFR-1794
=> DFR-1794 invalid field removed

charts/finrem-cos/Chart.yaml, charts/finrem-cos/values.preview.template.yaml, charts/finrem-cos/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-2799
Prs are building 4 pods, I believe its maxing out due to new memory based autoscaling in base chart
```
[ ] Yes
[ ] No
```
=> Finesse Autoscaling

charts/finrem-cos/Chart.yaml, charts/finrem-cos/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-2799
=> Raise mem limit

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/TestSetUpUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/correspondence/hearing/FormCandGCorresponderTest.java, src/test/resources/fixtures/latestConsentedConsentOrder/validate-form-a-collection.json
[DFR-1831](https://tools.hmcts.net/jira/browse/DFR-1831)
Fix copy of form a pension doc issue
```
[ ] Yes
[x ] No
```
=> DFR-1831: Fix copy of form a

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandler.java
DFR-1838
: send order null pointer
```
[ ] Yes
[x] No
```
=> DFR-1838: send order null pointer

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ManualPaymentAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/EventType.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/TestSetUpUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ManualPaymentAboutToSubmitHandlerTest.java
DFR-1832
Manual payment Copy of form A - convert to pdf
```
[ ] Yes
[ ] No
```
=> DFR-1832: Manual payment Copy of form A - convert to pdf

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/IdamAuthService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-1834
=> Dfr 1834 bugfix ccd conc issue

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/JudgeType.java
DFR-1670
proper officer of the court option added
```
[ ] Yes
[ ] No
```
=> DFR-1670: proper officer of the court option added

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/managebarrister/ManageBarristerAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/managebarrister/ManageBarristerAboutToStartHandlerTest.java
DFR-1883
Barrister access- Fix FieldShowCondition
```
[ ] Yes
[x] No
```
=> DFR-1883: Barrister access- Fix FieldShowCondition

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/bulkscan/CcdBulkScanIntegrationTest.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/caseorchestration/ConsentOrderApprovedTest.java, src/functionalTests/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/HearingNonFastTrackDocumentTest.java
=> dfr-1199 checking pipeline

charts/finrem-cos/Chart.yaml, charts/finrem-cos/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-2946
=> add dgcs secrets to chart

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendApplicationAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/IssueApplicationConsentedAboutToStartHandler.java, src/main/resources/application.properties, src/test/resources/application.properties
=> dfr-1199 removing defaults

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ApprovedOrderNoticeOfHearingService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctions.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedOrderApprovedLetterService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/BaseServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ApprovedOrderNoticeOfHearingServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedOrderApprovedLetterServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterServiceTest.java
[DFR-1921](https://tools.hmcts.net/jira/browse/DFR-1921)
Fix date issue with doc generation since DFR-1199
```
[ ] Yes
[ x] No
```
=> DFR-1921: Fix date issue with doc generation since DFR-1199

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/notification/NotificationTests.java, src/functionalTests/resources/application.properties, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FinremNotificationServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java, src/test/resources/application.properties
DFR-1938
remove prepare for hearing notification
```
[ ] Yes
[x] No
```
=> DFR-1938: remove prepare for hearing notification

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/miniformacontested/ContestedMiniFormADetailsMapper.java
=> DFR-1963: INCIDENT: Issue application error

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/OrderRefusalOption.java
=> DFR-1958: INCIDENT: List for hearing error

audit.json, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/IssueApplicationContestedSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/solicitors/CheckSolicitorIsDigitalService.java
fix security scan and improve logging
=> fix security scan and improve logging

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/rejectedorder/RejectedOrderDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/OrderRefusal.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/letterdetails/TranslatedOrderRefusalDocument.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/rejectedorder/RejectedOrderDetailsMapperTest.java
Dfr 1991
order refusal date
```
[ ] Yes
[ ] No
```
=> Dfr 1991 order refusal date

build.gradle
=> Excluding FinremCaseData Test

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ValidateHearingService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentControllerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/HearingNonFastTrackDocumentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ValidateHearingServiceTest.java, src/test/resources/fixtures/contested/validate-hearing-withoutfastTrackDecision.json
https://tools.hmcts.net/jira/browse/DFR-2004
list for hearing - moved bulkprint logic into submit handler
```
[ ] Yes
[ ] No
```
=> DFR-2004: list for hearing - moved bulkprint logic into submit handler

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterService.java
https://tools.hmcts.net/jira/browse/DFR-2014
general letter - unprocessable entity error
```
[ ] Yes
[ ] No
```
=> DFR-2014: general letter

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentGeneratorService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentControllerTest.java, src/test/resources/fixtures/bulkprint/bulk-print-additional-hearing-confidential.json
DFR-2004
Improve logging adding caseId
```
[ ] Yes
[ ] No
```
=> DFR-2004: Improve logging adding caseId

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentGeneratorService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentGeneratorServiceTest.java
DFR-2023
stop sending recipient to send letter request
```
[ ] Yes
[ ] No
```
=> DFR-2023: stop sending recipient to send letter request

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/solicitors/RemovedSolicitorService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/solicitors/RemovedSolicitorServiceTest.java
DFR-2024
handling nullpointer in remove solicitor service
```
[ ] Yes
[x] No
```
=> DFR-2024: handling nullpointer in remove solicitor service

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DocumentManagementService.java
DFR-615
fix auth issue
```
[ ] Yes
[ ] No
```
=> DFR-615: fix auth issue

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/evidencemanagement/EvidenceManagementUploadService.java
DFR-615
update log
```
[ ] Yes
[ ] No
```
=> DFR-615: update log

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/ListForHearingTask.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/utils/csv/CaseReference.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/utils/csv/CaseReferenceCsvLoader.java
DFR-2057: Re-run 'List for Hearing' event for identified cases in bulk
```
[ ] Yes
[ ] No
```
=> DFR-2041: Rerun in bulk the 'Send Order' event for identified cases

build.gradle, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelperTest.java
=> Fix test for mutation suite

build.gradle, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelperTest.java
=> Fix mutation test

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendApplicationAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderConsentedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderConsentedAboutToSubmitHandler.java
=> Dfr 2085 fix intervener issue

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UploadContestedCaseDocumentsAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignCaseAccessService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/FdrDocumentsHandler.java
DFR-2097
FR Contested:Upload case files error
```
[ ] Yes
[ ] No
```
=> DFR-2097: upload fdr document using uploadcasefiles event

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/GeneralLetter.java
=> DFR-2102 FR Contested: General email and letter error

build.gradle
=> DFR-2072: Guava Vulnerability

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenericDocumentService.java
DFR-2114
approved consent order - convert pension document in pdf
```
[ ] Yes
[x] No
```
=> DFR-2114: approved consent order - convert pension document in pdf

src/main/resources/json/court-details.json, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctionsTest.java
DFR-2132
Update Leyland address
```
[ ] Yes
[ ] No
```
=> DFR-2132: Update Leyland address

build.gradle
=> changed mutation threadhold limit

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentGeneratorService.java
(https://tools.hmcts.net/jira/browse/DFR-2162)
revert recipient name from bulk print request
```
[ ] Yes
[ ] No
```
=> DFR-2162: revert recipient name from bulk print request

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentGeneratorService.java
Reverts hmcts/finrem-case-orchestration-service#1086
=> Revert "DFR-2162: revert recipient name from bulk print request"

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/CaseUsers.java
DFR-2123: 
fix caseRole
```
[ ] Yes
[ ] No
```
=> DFR-2123: fix caseRole

build.gradle
=> DFR-2030: Fix spring security vuln

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/UploadCaseDocumentWrapper.java
https://tools.hmcts.net/jira/browse/DFR-2188
=> DFR-2188 not serialising empty collections

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java
https://tools.hmcts.net/jira/browse/DFR-2187
=> don't save empty collections

Jenkinsfile_CNP, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/FinremCaseDataTest.java
=> revert temporary remove copyartifact

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/RejectGeneralApplicationSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/PaperNotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/helper/DocumentHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/RejectGeneralApplicationSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/PaperNotificationServiceTest.java, src/test/resources/fixtures/refusal-order-contested.json
=> DFR-2084: Letter correspondence interveners - System Generated

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/CreateGeneralLetterAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/CreateGeneralLetterAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/FinremNotificationRequestMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/AddresseeGeneratorHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/generalletter/GeneralLetterDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/GeneralLetterWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/IntervenerShareDocumentsService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/CreateGeneralLetterAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/generalletter/GeneralLetterDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetServiceFinremTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ManualPaymentDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-2069
```
[ ] Yes
[x ] No
```
=> Dfr 2069 update general letter correspondence for intervener roles

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/RemoveApplicantDetailsController.java
https://tools.hmcts.net/jira/browse/DFR-2212
=> DFR-2212 adding logs to contested

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ManageCaseDocumentsContestedAboutToSubmitHandler.java
https://tools.hmcts.net/jira/browse/DFR-2302
=> DFR-2302 NPE fix

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentGeneratorService.java
=> DFR-2238: Send letter setting for lower env

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterServiceTest.java, src/test/resources/fixtures/general-letter.json
DFR-2346
INC5549841
consent general letter missing respondent name in letter
=> DFR-2346: consent general letter missing respondent name in letter

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/sendorder/SendOrderApplicantDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/sendorder/SendOrderIntervenerFourDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/sendorder/SendOrderIntervenerOneDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/sendorder/SendOrderIntervenerThreeDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/sendorder/SendOrderIntervenerTwoDocumentHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/sendorder/SendOrderRespondentDocumentHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentServiceTest.java
DFR-2338
Order should appear newest at top in Send Order
```
[ ] Yes
[ ] No
```
=> DFR-2338: Order should appear newest at top in Send Order

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java
DFR-2354
send order event - nullpointer exception
=> DFR-2354: send order event

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ManageCaseDocumentsContestedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ManageCaseDocumentsContestedAboutToSubmitHandlerTest.java
DFR-2357
manage case document npe - added fix
=> DFR-2357: manage case document npe - added fix

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/FinremNotificationRequestMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
[DFR-2343](https://tools.hmcts.net/jira/browse/DFR-2343)
Add validation for intervener emails
```
[ ] Yes
[x ] No
```
=> Dfr 2343 Fix issues with emails for intervener actions

charts/finrem-cos/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSSE-3944
move to Workload Identity
=> Update Identity Chart.yaml

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderConsentedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderConsentedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/DFR-2398
convert to pdf before sending for stamping
=> DFR-2398: convert to pdf before sending for stamping

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsService.java
adding log message to trap in AppInsight
=> adding log message to trap in AppInsight

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentGeneratorService.java
=> improve log message

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/RemoveApplicantDetailsController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/nocworkflows/UpdateRepresentationWorkflowService.java
=> corrected log message

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/GeneralApplicationRemoveTask.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java, src/main/resources/application.properties, src/main/resources/generalApplicationRemoveCaseReferenceList.csv, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdServiceTest.java, src/test/resources/application.properties, src/test/resources/fixtures/general-application-duplicate.json
=> Dfr 2388 remove duplicate ga

src/main/resources/application.properties, src/test/resources/application.properties
=> DFR-2388: FR Contested: remove duplicated general applications

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsServiceTest.java
Reverts hmcts/finrem-case-orchestration-service#1255
=> Revert "Dfr 2412 Send general application notifications when received from caseworker"

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelperTest.java
=> fix code smell

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentgenerator/BulkPrintDocumentServiceTest.java
DFR-2473
check for empty uploaded document.
=> DFR-2473: check for empty uploaded document.

build.gradle
=> DFR-2484: Exception in ClassLoader - NoSuchMethodError

acb.tpl.yaml
DFR-2529
microsoft suggested patch - to deal with no more retries left
=> DFR-2529: microsoft suggested patch - to deal with no more retries left

README.md, acb.tpl.yaml
=> patch - no more retries left

Jenkinsfile_nightly
DFR-2547
disable mutation tests
=> DFR-2547: disable mutation tests

Jenkinsfile_nightly, build.gradle
DFR-2543
Enable mutation tests
=> DFR-2543: Enable mutation tests

.github/renovate.json
https://tools.hmcts.net/jira/browse/DFR-2549
=> DFR-2549 setting time for renovate

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/Court.java
=> DFR-2487: highcourt enum

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateCourtInfoAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DefaultCourtListWrapper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateCourtInfoAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/CourtDetailsMapperTest.java
https://tools.hmcts.net/jira/browse/DFR-2565
=> DFR-2565 fix for consented court mapping

.github/renovate.json
=> fix renovate schedule

build.gradle, config/owasp/suppressions.xml
=> Suppress logback cve

config/owasp/suppressions.xml
=> supress CVE-2023-6481

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendApplicationConsentedMidHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SolicitorCreateConsentedMidHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendApplicationConsentedMidHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SolicitorCreateConsentedMidHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderServiceTest.java
DFR-2593
Solicitor create/Amend mid event - npe
=> DFR-2593: Solicitor create/Amend mid event - npe

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/caseorchestration/RejectedOrderDocumentTest.java, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java
Reverts hmcts/finrem-case-orchestration-service#1482
=> Revert "ignore failing FT"

build.gradle
=> Fix local env

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderServiceTest.java
DFR-2617
send order - general order
=> DFR-2617: send order - general order

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralEmailService.java
DFR-2625
create general email npe
=> DFR-2625: create general email npe

config/owasp/suppressions.xml
=> remove suppression

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/DirectionUploadOrderSubmittedHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/DirectionUploadOrderSubmittedHandlerTest.java
=> Remove selected Parties from process order

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/payments/PaymentServiceTests.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/correspondence/hearing/FinremAdditionalHearingCorresponder.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/correspondence/hearing/FinremAdditionalHearingCorresponderTest.java
=> Dfr 2688 fix nullpointer

config/owasp/suppressions.xml, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/payments/PaymentServiceTests.java
=> DFR-2688: Enable test

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/shareselecteddocuments/ShareSelectedDocumentsAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/shareselecteddocuments/ShareSelectedDocumentsAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/shareselecteddocuments/ShareSelectedDocumentsAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/shareselecteddocuments/ShareSelectedDocumentsAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/DFR-2332
Move handlers into separate package
Fix minor typos
=> Refactor Share Selected Documents handlers

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CaseDocumentType.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/OtherDocumentsHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ManageCaseDocumentsContestedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ManageCaseDocumentsContestedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/shareselecteddocuments/ShareSelectedDocumentsAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ApplicantShareDocumentsServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/IntervenerShareDocumentsServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RespondentShareDocumentsServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/LegacyConfidentialDocumentsServiceTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/applicant/ApplicantOtherDocumentsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerfour/IntervenerFourOtherDocumentsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerone/IntervenerOneOtherDocumentsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerthree/IntervenerThreeOtherDocumentsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenertwo/IntervenerTwoOtherDocumentsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/respondent/RespondentOtherDocumentsCollectionServiceTest.java
=> DFR-2753: FR Restore CaseDocumentType

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandlerTest.java
DFR-2771
send order error - general order array do not contains doc
=> DFR-2771: send order error - general order array do not contains doc

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-2808
Remove redundant CCD API call
=> Remove redundant CCD API call

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java
https://tools.hmcts.net/jira/browse/DFR-2808
Add Javadoc for CCD event API calls
=> Add javadoc for CCD case updates

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcategory/GeneralApplicationsCategoriserTest.java
https://tools.hmcts.net/jira/browse/DFR-2917
Remove Java assertions from unit tests
=> Remove Java assertions from unit tests

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcatergory/UploadGeneralDocumentsCategoriser.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcatergory/UploadGeneralDocumentsCategoriserTest.java
https://tools.hmcts.net/jira/browse/DFR-2973
Refactor UploadGeneralDocumentsCategoriserTest code prior to NPE fix
=> Refactor UploadGeneralDocumentsCategoriserTest

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcatergory/HearingNoticesCategoriserTest.java
Remove Java assertions from HearingNoticeCategoriserTest
=> Remove Java assertions from HearingNoticeCategoriserTest

Jenkinsfile_nightly
Update nightly build to start at 3am
=> Update nightly build to start at 3am

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/CaseDocumentsHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/CaseDocumentsHandlerTest.java
[DFR-2981](https://tools.hmcts.net/jira/browse/DFR-2981)
=> Add conditional statement for null caseDocumentType.

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/DocumentHandler.java
[DFR-2994](https://tools.hmcts.net/jira/browse/DFR-2994)
=> Use try catch block to log error.

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvMigrationTask.java
https://tools.hmcts.net/jira/browse/DFR-2797
Add Solicitor Draft Order state to CFV migration case search
Fix potential for searchResults NPE
=> DFR-2797 Add Solicitor Draft Order to CFV migration

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/DocumentHandler.java
[DFR-2994](https://tools.hmcts.net/jira/browse/DFR-2994)
Close detail ( T )
DTS Divorce and Financial Remedy
=> Dfr 2994 cfv document handler apply document category npe

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvMigrationTask.java
https://tools.hmcts.net/jira/browse/DFR-2797
Change elasticsearch query for searching for cases for CFV migration
- put state query into filter context so it does an exact match
- temporarily log the reference of any cases found rather than process in order to check query is working
=> DFR-2797 Update migration task ES query

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvMigrationTask.java
https://tools.hmcts.net/jira/browse/DFR-2797
Enable cases to be processed with new CFV migration query
=> DFR-2797 Enable cases to be processed with new query

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvMigrationTask.java
https://tools.hmcts.net/jira/browse/DFR-2797
Add missing states to CFV migration task
=> Add missing states to CFV migration task

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CcdCallbackController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/CfvMigrationWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvMigrationTask.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvUpdateTask.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvUpdateTaskDocumentCategoriser.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvUpdateTaskTest.java
https://tools.hmcts.net/jira/browse/DFR-3032
Create cronjob task to update documents with latest CFV categorisation fixes
=> DFR-3032 CFV update task

README.md
Update README with application logs directory
=> Update README with application logs directory

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/CfvMigrationWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvUpdateTask.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CfvUpdateTaskTest.java
https://tools.hmcts.net/jira/browse/DFR-3032
Add searchable CFV update field
=> Add searchable CFV update field

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/UpdateContestedCaseController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/UpdateContestedCaseControllerTest.java, src/test/resources/fixtures/contested/remove-complexity-details.json
https://tools.hmcts.net/jira/browse/DFR-3077
Remove reference to invalid, non-existent field
=> DFR-3077 Remove invalid field reference

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendPaperApplicationContestedAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnStartDefaultValueService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendPaperApplicationContestedAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnStartDefaultValueServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-3051
Refactor Amend Paper Application Details About to Start handler
=> Dfr 3501 refactor paper amend handler

src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/caseorchestration/AmendCaseDetailsTest.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/UpdateContestedCaseController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/UpdateContestedCaseControllerTest.java
[DFR-3079](https://tools.hmcts.net/jira/browse/DFR-3079)
We don't want to make these values null anymore. So the method becomes redundant.
=> Remove unnecessary method and always update complexity details.

build.gradle, src/main/resources/application-local.properties
https://tools.hmcts.net/jira/browse/DFR-3152
Setting local environment logging level to debug
=> DFR-3152 Setting local environment logging level to debug

README.md
=> Add sonar badges

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DFR-3237
Set nightly pipeline to run at 17:45
=> Set nightly pipeline to run at 17:45

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/BulkAddOrganisationPolicyTask.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/nocworkflows/UpdateRepresentationWorkflowService.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/BulkAddOrganisationPolicyTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UpdateRepresentationWorkflowServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-3261
Add scheduled task to add missing organisation policy data
=> DFR-3261: Add scheduled task to add missing organisation policy data

build.gradle, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/GeneralApplicationStatus.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/IntervenerService.java
Configure checkstyle and fix issues
=> Configure checkstyle and fix issues

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/ServiceAuthTokenGeneratorConfiguration.java
https://emea.fortify.com/Applications/31336/Issues?t=-5101&d=450000000
Removed log that Fortify objects too.  Confirmed that the bean is still in use.
Unit tests pass
=> Removed log line that writes auth token

build.gradle
Fix Caused by: java.lang.ClassNotFoundException: org.aspectj.lang.ProceedingJoinPoint when running bootWithCCD
=> Add spring-aspects to cftlib dependencies

build.gradle, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationMidHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignCaseAccessService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationService.java
See [DFR-2698](https://tools.hmcts.net/jira/browse/DFR-2698)
Add additional logging to Create General Application event.
=> Add GA logs to help troubleshoot GA not created bug

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AgreedDraftOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AgreedDraftOrderCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/DraftOrderReview.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/DraftOrderReviewCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/SuggestedDraftOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/SuggestedDraftOrderCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DraftOrdersWrapper.java
=> Dfr 3278 initial wrapper setup

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/AgreedDraftOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/DraftOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/DraftOrderCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/OrderStatus.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/OrderToBeReviewed.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/PensionSharingAnnex.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/PensionSharingAnnexCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DraftOrderService.java
Merge data model from https://github.com/hmcts/finrem-case-orchestration-service/pull/1896
=> Add data model

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingServiceTest.java
See [DFR-3377](https://tools.hmcts.net/jira/browse/DFR-3377)
Add `HearingService` to grep all hearing details and return a DynamicList
=> DFR-3377 CT: Hearing Details Dynamic List

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/CaseDocumentCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/agreed/AgreedDraftOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/agreed/AgreedDraftOrderCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/review/DraftOrderDocumentReview.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/suggested/SuggestedDraftOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/suggested/SuggestedDraftOrderCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DraftOrdersWrapper.java
https://tools.hmcts.net/jira/browse/DFR-3304
Add Case Documents data model
=> Add case documents data model

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GenericAboutToStartOrSubmitCallbackResponse.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CallbackDispatchService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersSubmittedHandlerTest.java
DFR-3304: Add Upload draft orders submitted handler
=> DFR-3304: Add Upload draft orders submitted handler

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DraftOrdersWrapper.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorder/upload/UploadDraftOrderAboutToStartHandlerTest.java
DFR-3304: Show upload party question only if user is a caseworker
=> DFR-3304: Show upload party question only if user is a caseworker

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/OrchestrationConstants.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersAboutToStartHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/upload/agreed/AgreedDraftOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/upload/agreed/AgreedDraftOrderAdditionalDocumentsCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/upload/agreed/AgreedDraftOrderCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/upload/agreed/AgreedPensionSharingAnnex.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/upload/agreed/AgreedPensionSharingAnnexCollection.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/upload/agreed/UploadAgreedDraftOrder.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorder/upload/UploadDraftOrderAboutToStartHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorder/upload/UploadDraftOrderAboutToSubmitHandlerTest.java
See [DFR-3388](https://tools.hmcts.net/jira/browse/DFR-3388)
Upload Agreed Order Page
=> DFR-3388(DFR-3319-1) Upload Agreed Order Page

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersAboutToStartHandler.java
Refactor about to start handler
=> Fix solicitor upload party question.

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersMidEventHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DraftOrdersWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/utils/FileUtils.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrderMidEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/utils/FileUtilsTest.java
See [DFR-3319](https://tools.hmcts.net/jira/browse/DFR-3319)
=> DFR-3319 Mid event to ensure Non-Word documents

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrderAboutToStartHandlerTest.java
Add test for upload suggested draft orders about to start handler
=> Add test for upload suggested draft orders about to start handler

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/CCDConfigValidator.java
=> DFR-3304: Fix finremcasedatatest

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/YesOrNo.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/agreed/AgreedDraftOrder.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DraftOrdersWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DraftOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrderAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/YesOrNoTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/DraftOrderServiceTest.java
See [DFR-3319](https://tools.hmcts.net/jira/browse/DFR-3319)
=> DFR-3319 Upload agreed order

build.gradle, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/NotificationRequestMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseDataService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctions.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentHearingService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GenerateCoverSheetService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java
=> Checkstyle upgrade and fixes

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java
https://tools.hmcts.net/jira/browse/DFR-3068
Added new applicantInRefuge field
Manual CCD tests
=> Added new applicantInRefuge FinremCaseData field

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingServiceTest.java
=> Dfr 3440 change upload agreed draft order hearing date format

bin/bulk-scan-validation-test.sh, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/error/GlobalExceptionHandler.java
https://tools.hmcts.net/jira/browse/DFR-3470
Suppress logging of stacktrace for bulk scan validation requests.
=> DFR-3470: Suppress logging of bulk scan validation exceptions

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/NotificationRequestMapper.java
https://tools.hmcts.net/jira/browse/DFR-3483
Stop email address from being written to logs
=> DFR-3483: Stop email address from being written to logs

build.gradle
https://tools.hmcts.net/jira/browse/DFR-3488
Reduce mutation threshold for pitest to enable nightly pipeline to complete
=> DFR-3488: Reduce mutation threshold for pitest

build.gradle
Mutation tests are failing due to score below threshold - reduce threshold for green pipeline until mutation testes fixed.
=> Reduce mutation test threshold

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/draftorders/HasApprovableCollectionReader.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/judgeapproval/RefusedOrderProcessor.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/draftorders/HasApprovableCollectionReaderTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/judgeapproval/RefusedOrderProcessorTest.java
=> Refactoring - HasApprovableCollectionReader

build.gradle
https://tools.hmcts.net/jira/browse/DFR-3488
Further reduce pitest mutation threshold to get nightly build passing.
=> DFR-3488: Reduce mutation threshold

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderServiceTest.java
See [DFR-3336](https://tools.hmcts.net/jira/browse/DFR-3336)
=> Refactoring GeneralOrderServiceTest

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedSubmittedHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/SendOrderWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendConsentOrderInContestedSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/FinremCaseDetailMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralOrderServiceTest.java
See [DFR-3516](https://tools.hmcts.net/jira/browse/DFR-3516)
=> DFR-3516 Refactoring

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/SendOrderWrapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/sendorder/SendOrderPartyDocumentHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendConsentOrderInContestedSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedSubmittedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentchecker/DuplicateFilenameDocumentCheckerTest.java
See [DFR-3516](https://tools.hmcts.net/jira/browse/DFR-3516)
Move `additionalDocument` to `SendOrderWrapper`
=> DFR-3516 Move additionalDocument to sendOrderWrapper

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandlerTest.java
https://tools.hmcts.net/jira/browse/DFR-3336
=> DFR-3336: Fix for prod release

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentServiceTest.java
=> Unit test for additional hearing document service

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingOrderController.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingOrderService.java
Add logging for Draft Approved Order event
=> Add logging for Draft Approved Order event

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java
Refactor and add logging for Process Order next hearings
=> Refactor and add logging for Process Order next hearings

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/DirectionUploadOrderAboutToSubmitHandler.java
Fix handler logging incorrect callback type
=> Fix logging of callback type

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/FeeLookUpTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/MiamCheckTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/NotificationsTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/PBAPaymentConfirmationTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/PBAPaymentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/PBAValidationTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/client/EmailClientTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/service/EmailServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-2773
Several functional tests are marking the Spring context as dirty and forcing it to be reloaded for every test method.
This isn't necessary and causes tests to run much slower than they should
=> DFR-2773: Improve test performance

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CcdCallbackController.java
Add the callback type in order to improve callback handled log
=> Improve callback handled log

Dockerfile, README.md, acb.tpl.yaml, build.gradle, src/functionalTests/resources/application-aat.properties, src/functionalTests/resources/application-local.properties, src/functionalTests/resources/application.properties, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/FeeLookUpTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/MiamCheckTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/NotificationsTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/PBAPaymentConfirmationTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/PBAPaymentTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/PBAValidationTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/client/EmailClientTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/service/EmailServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-3162
Java 21 upgrade
=> DFR-3162: Java 21 upgrade

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/PaperCaseCreateContestedAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/PaperCaseCreateContestedAboutToSubmitHandlerTest.java
See [DFR-3617](https://tools.hmcts.net/jira/browse/DFR-3617)
Set express pilot enrolment in paper case behind feature toggle. (Amend application does not need updating as it goes through the same controller endpoint as Form A). 
Manual and Unit
=> DFR-3617 Set express pilot enrolment in paper case

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingServiceTest.java
See [DFR-3622] (https://tools.hmcts.net/jira/browse/DFR-3622)
=> DFR-3622 CT: Upload draft orders shows (unknown) hearing

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/FinremCaseDetailMapperTest.java
https://tools.hmcts.net/jira/browse/DFR-2259
Code tidy-up
=> DFR-2259: Code tidy-up

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/judgeapproval/ApproveDraftOrdersMidEventHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/judgeapproval/ApproveDraftOrdersMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/DFR-3669
Revert change from DFR-3607 as it prevents judge Approve orders event from submitting
=> DFR-3669: Revert change from DFR-3607

build.gradle, config/checkstyle/checkstyle.xml, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/service/EmailService.java
Add checkstyle rules for:
- Newline at the end of a file
- No multiple blank lines
=> Add checkstyle rules

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingServiceTest.java
https://tools.hmcts.net/jira/browse/DFR-3679
Reorganise methods in HearingServiceTest so it is easier to understand
=> DFR-3679: Reorganise methods in HearingServiceTest

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersAboutToSubmitHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersAboutToSubmitHandlerTest.java
[DFR-3697](https://tools.hmcts.net/jira/browse/DFR-3697)
=> Dfr 3697 judge unable to approve order as not displaying on draft orders tab

src/main/resources/resendlistforhearing-encrypted.csv
https://tools.hmcts.net/jira/browse/DFR-3710
Add 2 cases for Resend List For Hearing cron job
=> DFR-3710: Add cases

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationAboutToSubmitHandler.java
https://tools.hmcts.net/jira/browse/DFR-2698
Remove logging that is no longer required as this is just creating noise in the prod alerts channel
=> DFR-2698: Remove logging that is no longer required

build.gradle, settings.gradle
Add jitpack for some dependencies that have not migrated to Azure yet.
=> Add jitpack for some dependencies

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentController.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentControllerTest.java
https://tools.hmcts.net/jira/browse/DFR-3788
Revert removing case submission about to submit endpoint so that finrem-cos can be deployed before updating CCD defs
Tested in preview to ensure the E2E tests run using this finrem-cos image and the latest CCD defs
=> Revert removing /pba-payment endpoint

build.gradle, src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/caseassignment/AssignCaseServiceConsumerTest.java, src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/ccddatastore/CaseDataStoreServiceConsumerContractTest.java, src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/ccddatastore/GetUserRolesConsumerTest.java, src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/ccddatastore/SearchUserRolesConsumerTest.java, src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/payments/FeeLookupConsumerTest.java, src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/payments/PBAValidateConsumerTest.java, src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/payments/SidamConsumerTest.java, src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/rdprofessional/PrdOrganisationServiceConsumerContractTest.java
https://tools.hmcts.net/jira/browse/DFR-3959
Remove checkstyle errors from contract tests
=> DFR-3959: Remove checkstyle errors from contract tests

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelperTest.java
https://tools.hmcts.net/jira/browse/DFR-3957
Refactor GenerationApplicationHelperTest
=> DFR-3957: Refactor general application helper test

README.md, build.gradle, src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/notification/NotificationTests.java, src/functionalTests/resources/application.properties, src/functionalTests/resources/json/contested/update-frc-info.json
Fix ignored functional test
Update checkstyle max warnings
=> DFR-3915: Fix ignored NotificationTest

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/generalapplicationdirections/GeneralApplicationDirectionsNewEventAboutToSubmitHandler.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/generalapplicationdirections/GeneralApplicationDirectionsNewEventAboutToSubmitHandlerTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsServiceTest.java
[DFR-3652](https://tools.hmcts.net/jira/browse/DFR-3652)
- This change prevents us from generating a duplicate hearing document.
- Retrieves the hearing notice through our get method instead.
=> Dfr 3652 refactor document generator for hearing notice for General Applications Directions event

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/formc/FormCLetterDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/managehearings/ManageHearingFormCLetterDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/letterdetails/FormCLetterDetails.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/letterdetails/managehearings/FormCLetterDetails.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseHearingFunctions.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/formc/FormCLetterDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/managehearings/ManageHearingFormCLetterDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java
See [DFR-4055](https://tools.hmcts.net/jira/browse/DFR-4055)
=> DFR-4055  Fix express form C template

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
=> DFR-3915: Remove redundant code

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/notificationrequest/FinremNotificationRequestMapperTest.java
Improve general email unit tests.
Existing unit tests don't check the value of the email body.
=> DFR-3915: Improve general email unit tests

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/ContactDetailsValidator.java
Moving private method to the bottom of the file.
=> Refactoring ContactDetailsValidator

build.gradle
=> Remove jaxbOsgi

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/contested/mh/UploadApprovedOrderMhContestedAboutToStartHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/contested/mh/UploadApprovedOrderContestedMhAboutToStartHandlerTest.java
[DFR-4123](https://tools.hmcts.net/jira/browse/DFR-4123)
- Set isFinalOrder to null on Upload Approved Order Event
- Set isAddHearingChosen to null on Upload Approved Order Event
=> Dfr 4123 remove pre populated fields on second run of upload approved order event

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/contested/mh/UploadApprovedOrderContestedMhMidHandler.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/contested/mh/UploadApprovedOrderContestedMhMidHandlerTest.java
See [DFR-4125](https://tools.hmcts.net/jira/browse/DFR-4125)
1. Add validation for emptiness – ensure the `uploadHearingOrders` is not empty or null.
2. Remove checking for non-event property `uploadAdditionalDocument`
=> DFR-4125 CT: UAO – Additional Order Attachments incorrectly become mandatory after removal or when multiple orders are added

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnlineFormDocumentService.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnlineFormDocumentServiceTest.java
=> Remove generateContestedMiniFormA

src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralLetterService.java, src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcategory/CreateGeneralLetterDocumentCategoriser.java, src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcategory/CreateGeneralLetterDocumentCategoriserTest.java
See [DFR-3812](https://tools.hmcts.net/jira/browse/DFR-3812)
1. Make “generatedLetter” deletable
=> DFR-3812 Make “generatedLetter” deletable

src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/FinremCallbackRequestFactory.java
=>  refactor FinremCallbackRequestFactory
