hmcts/finrem-case-orchestration-service

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceController.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseMaintenanceControllerTest.java
- src/test/resources/fixtures/contested/amend-divorce-details-decree-absolute.json
- src/test/resources/fixtures/contested/amend-divorce-details-decree-nisi.json
- feedback change for divorce petition issued date
- Divorce petition issued Date is mandatory field.
https://tools.hmcts.net/jira/browse/FR-974
Petition Date should be captured - regardless of whether the petition is issued or not
```
[ ] Yes
[ X] No
```
> FR-974-divorce_petition_issued_date_for_amend_application

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/NotificationsTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
- removed authToken as it is not required for notification api.
https://tools.hmcts.net/jira/browse/FR-820
removed authToken as it is not required for notification api.
```
[ ] Yes
[X ] No
```
> FR-820_remove_unused_auth_headers

- dependency-check-suppressions.xml
Added suppressions for vulnerabilities introduced from some dependencies of Eclipse Jetty. 
- CVE-2019-17632 (Default unhandled Error response content does not escape Exception messages in stacktraces included in error output)
- A prototype pollution vulnerability in handlebars is exploitable if an attacker can control the template inside "javascript/handlebars\.js"
> Added suppressions to remove unfixable vulnerabilities

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/UpdateController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/bulkscan/transformation/output/CaseCreationDetails.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/bulkscan/update/in/transformation/in/BulkScanCaseUpdateRequest.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/bulkscan/update/in/transformation/output/SuccessfulUpdateResponse.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/bulkscan/UpdateControllerTest.java
https://tools.hmcts.net/jira/browse/BSP-145
Created a new "Update case" endpoint for Bulk Scanning. At the moment this endpoint will not be used however it will be called in the future by the RBS team to trigger an update to an existing case in CCD. Currently no logic is introduced, the endpoint just returns a 200 response code.
> BSP-145: Added update case endpoint for future use by BSP

- build.gradle
- src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/bulkscan/BulkScanIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkScanController.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/BulkScanControllerTest.java
https://tools.hmcts.net/jira/browse/BSP-155
endpoint `POST /update-case` is not needed for now in FR COS. It will always return NOT_IMPLEMENTED status code
```
[x] Yes
[ ] No
```
> BSP-155: POST /update-case is not implemented in FR cos

- src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/caseorchestration/AmendCaseDetailsTest.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/CcdDataMigrationController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DraftOnlineDocumentController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/UpdateConsentedCaseController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataControllerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/RemoveApplicantDetailsControllerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java
- Added new constants for SOLICITOR_AGREE_TO_RECEIVE_EMAILS and PAPER_APPLICATION
- Removed duplicate YES & NO constants that were in both CCD config constants and orchestration constants
- Removed redundant empty lines
- Removed "throws Exception" from tests that don't throw exceptions
> Minor code cleanup

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/OcrFieldName.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/helper/BulkScanHelper.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java
- BSP-375: Added additional transformation for 'solicitorEmail' (If 'solicitorEmail' field is populated, then add the value 'Yes' to the field 'solicitorAgreeToReceiveEmails'.)
- BSP-376: Additional transformation for 'rSolicitorName' to 'appRespondentRep' (If 'rSolicitorName' is empty, then make ''appRespondentRep' is set to 'No', If 'rSolicitorName' is not empty, then make ''appRespondentRep' is set to 'Yes')
> BSP-375 & BSP-376: Added additional transformation for 'solicitorEmail' & 'rSolicitorName'

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/helper/BulkScanHelper.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/transformation/FormAToCaseTransformerTest.java
There was a bug with a redundant comma that caused a difference between the validation and transformation logics for BSP.
'I am represented by a solicitor in these proceedings, who has signed Section 5, and all documents for my attention should be sent to my solicitor whose details are as follows'
so it is now:
''I am represented by a solicitor in these proceedings, who has signed Section 5 and all documents for my attention should be sent to my solicitor whose details are as follows''
> Removed comma from applicantRepresentedPaper value

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/OrchestrationConstants.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/DocumentConfiguration.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/document/CtscContactDetails.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AbstractDocumentService.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentService.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CommonFunction.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/BaseServiceTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/SetUpUtils.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsControllerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/NotificationsTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/document/CtscContactDetailsTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignedToJudgeDocumentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintServiceTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OnlineFormDocumentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RefusalOrderDocumentServiceTest.java
- src/test/resources/application.properties
Send 'your application has been assigned to judge' notification letter to applicant/applicant solicitor when event 'assign to judge' is used.
Note: These notification letters ARE NOT supposed to be viewable in CCD by the caseworker etc
> BSP-287: 'application assigned to judge' notification letter

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/NotificationsController.java
Flipped conditional logic so paperApplicant field takes preference and is checked before deciding whether to send email or letter.
_"Infer a 'yes'. Take the assumption that they have provided because they are happy to be contacted. This removes any decision-making for the caseworker. However, currently the triggers for emails are contingent on 'yes' being ticket, and we don't want paper applicants who have a 'yes' ticked for this to get emails (as they won't be able to login and see what the email is suggesting they should see."_
> Flipped conditional logic so paperApplicant field takes preference

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/mappers/ChildrenInfoMapper.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/validation/FormAValidator.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulk/scan/validation/FormAValidatorTest.java
https://tools.hmcts.net/jira/browse/FR-1691
Children's DoB in BSP should is currently failing validation if not provided even though it is NOT a mandatory field. I've added conditional logic to only apply validation if the values are actually present
> FR-1691: Updated validation logic to allow for childrens DoB to be empty

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
_As part of the CCD 19.1.1 release we have to revert the changes done in the JIRA ticket RDM-8751, 
Because the addition of the new field 'case_types_results' breaks the ccd-client library with exception Unrecognized field "case_types_results".
To address this issue, we have done changes in ccd-client version 4.7.3 library to ignore un-known json properties.
@JsonIgnoreProperties(ignoreUnknown = true) has been added on most of the model classes in the ccd-client library. Even if CCD adds new fields in the response objects in the future this change is going to protect the services from throwing errors on un-known properties
Could you please upgrade the version of ccd-client library (core-case-data-store-client) to latest 4.7.3 version. It should not break any functionality on services …
> Bumped CCD Client as per CCD teams request (also bumped Gradle version)

- build.gradle
Attempt to fix build error on master pipeline:
```
[2020-09-28T09:40:20.085Z] # A fatal error has been detected by the Java Runtime Environment:
[2020-09-28T09:40:20.085Z] #  SIGSEGV (0xb) at pc=0x00007fcbc5114820, pid=17685, tid=17722
```
> fix SIGSEGV jvm error on master build

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataControllerTest.java
- src/test/resources/fixtures/invalid-case-type.json
https://tools.hmcts.net/jira/browse/FR-1778
XUI use a version of our config to test and develop on share a case. We updated out config for demo and have it pre populating a field on our cases in callback. 
As they use a branched version of consent it also makes the callback but doesn't have the field which is being prepopulated on demo. So they can't make new cases.
This change simply checks the case type is consent or contested before prepopulating the field.
```
[ ] Yes
[x] No
```
> adding check for test type before setting default org policy

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderApprovedController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintService.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentService.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderPrintService.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderApprovedControllerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentServiceTest.java
https://tools.hmcts.net/jira/browse/RPET-707
- filtered out null pension documents when stamping
- improved logging adding case ID to log messages
```
[ ] Yes
[x] No
```
> RPET-707: filtering out null pension documents and improving logging

- README.md
- build.gradle
bug on the latest cft lib plugin won't pickup finrem secrets so we need the .aat-env file back
> reverting cft plugin upgrade

- src/cftlib/java/uk/gov/hmcts/reform/finrem/caseorchestration/CftLibConfig.java
IDAM_SUPER_USER was added to definitions as a new Role but wasn't updated in the cftlib config for COS causing it to fail on import
> Fix CFT lib missing role

- build.gradle
- config/owasp/suppressions.xml
[CVE-2023-34036](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-34036)  
Reactive web applications that use Spring HATEOAS to produce hypermedia-based responses might be exposed to malicious forwarded headers if they are not behind a trusted proxy that ensures correctness of such headers, or if they don't have anything else in place to handle (and possibly discard) forwarded headers either in WebFlux or at the level of the underlying HTTP server.
For the application to be affected, it needs to satisfy the following requirements:
*  It needs to use the reactive web stack (Spring WebFlux) and Spring HATEOAS to create links in hypermedia-based responses.
*  The application infrastructure does not guard against clients submitting (X-)Forwarded… headers.
> fix-depend-issue

- acb.tpl.yaml
```
[2023-11-16T12:20:13.983Z] 2023/11/16 12:20:03 Container failed during run: manifest-create, waiting 3 seconds before retrying...
[2023-11-16T12:20:13.983Z] 2023/11/16 12:20:06 Launching container with name: manifest-create
[2023-11-16T12:20:13.983Z] docker: Error response from daemon: Conflict. The container name "/manifest-create" is already in use by container "be3ec598485ee89ad9c037a48cbfb50fd4883939234d094a47948898d75ca46c". You have to remove (or rename) that container to be able to reuse that name.
[2023-11-16T12:20:13.983Z] See 'docker run --help'.
[2023-11-16T12:20:13.983Z] 2023/11/16 12:20:06 Container failed during run: manifest-create, waiting 3 seconds before retrying...
[2023-11-16T12:20:13.983Z] 2023/11/16 12:20:09 Launching container with name: manifest-create …
```
> Remove manifest before trying to create it

- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/spreadsheet/FinremCaseDataTest.java
https://tools.hmcts.net/jira/browse/DFR-2104
Created a new test to ensure that wrappers that are added to FInremCaseData include @JsonInclude(JsonInclude.Include.NON_NULL) or inherit it.
> DFR-2104 Validate FinremCaseData for all wrapper with JsonInclude NON_NULL

- build.gradle
During bootWithCCD startup, exceptions are thrown by ccd-definition-store-api due to failure to connect to the translation service. The exceptions can be avoided by disabling Welsh translations
> Fix bootWithCCD startup exceptions due to missing translation service

- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/FinremCallbackRequestFactory.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendApplicationAboutToStartHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/documentcatergory/AssignDocumentCategoriesAboutToSubmitHandlerTest.java
Unit tests are littered with long chains of builder code in order to create FinremCallbackRequests objects. This reduces the readability of tests.
Added factory class to abstract details of creating request object for unit tests.
Included some example usage
> Add factory class to create test objects

- build.gradle
- config/owasp/suppressions.xml
Suppress CVE-2024-25710 as bumping commons-compress causes compile errors
> Suppress CVE-2024-25710

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/UploadCaseDocument.java
https://tools.hmcts.net/jira/browse/DFR-2953
Add selectForUpdate field to UploadCaseDocument class to fix failing FinremCaseDataTest.
This field is used in Manage scanned documents only. However, the test is failing because the CCD data model is shared between Manage scanned documents and Manage case documents.
> DFR-2953: Fix FinremCaseDataTest

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/OtherDocumentsHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/applicant/ApplicantOtherDocumentsHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerfour/IntervenerFourOtherDocumentsHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerone/IntervenerOneOtherDocumentsHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerthree/IntervenerThreeOtherDocumentsHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenertwo/IntervenerTwoOtherDocumentsHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/respondent/RespondentOtherDocumentsHandler.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/applicant/ApplicantOtherDocumentsHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerfour/IntervenerFourOtherDocumentsHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerone/IntervenerOneOtherDocumentsHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenerthree/IntervenerThreeOtherDocumentsHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/intervenertwo/IntervenerTwoOtherDocumentsHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/casedocuments/respondent/RespondentOtherDocumentsCollectionServiceTest.java
[DFR-2923](https://tools.hmcts.net/jira/browse/DFR-2923)
Remove subfolder 'Pension Plan' within the 'Applicant Documents' folder
Remove subfolder 'Pension Plan' within the 'Respondent Documents' folder
Pension plan documents to go into 'Expert Reports' folder
FURTHER NOTE: Previously, the Intervener pension plan documents were moved to a another intervener category folder. However, this doesn't seem to be present in our ccd-definitions in categories.json. This is probably worth testing too.
> Dfr 2923 View pension documents in expert reports

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcatergory/UploadGeneralDocumentsCategoriser.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcatergory/UploadGeneralDocumentsCategoriserTest.java
https://tools.hmcts.net/jira/browse/DFR-2973
Uploaded documents with no document type should be categorised as Caseworker Uploaded Documents
> DFR-2973: Set category for uploaded documents with no document type

- build.gradle
https://tools.hmcts.net/jira/browse/DFR-3124
DFR-3124 Revert spring cloud bom version update as it causes cftlib to fail to start
> DFR-3124 Revert spring cloud bom version update

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/NotificationRequestMapper.java
https://tools.hmcts.net/jira/browse/DFR-3135
Add missing template personalisation to default to always null for deprecated /notify/assign-to-judge endpoint
> DFR-3135 Add in quick fix

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/UpdateRepresentationController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AssignCaseAccessService.java
https://tools.hmcts.net/jira/browse/DFR-3137
This is only to fix logging. DFR-3137 has highlighted that /apply-noc-decision **always** logged this message
```
log.info("The creator role has been revoked on case {}", caseDetails.getId()); 
```
But did this even when the CREATOR role **hadn't** been revoked.  This makes support more difficult.
Removed this log line, and added a little more log information to make tackling NOC issues more transparent.
> DFR-3137: Corrected so that logging in area of apply-noc-decision is correct

- .github/renovate.json
- build.gradle
Revert update to spring-cloud-dependencies as it breaks cftlib
Update renovate to ignore spring-cloud-dependencies
> Revert update to spring-cloud-dependencies

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformer.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/bulkscan/transformation/FormAToCaseTransformerTest.java
See [DFR-3231](https://tools.hmcts.net/jira/browse/DFR-3231)
Convert all empty string value mappings on case data fields null. Ideally I would want to validate that mandatory fields do not come through as empty strings when not provided. 
However, the method that defines the check for fields is within the Bulkscan library abstract class BulkScanFormValidator which or service validator inherits from - this method only checks for the presence and does not check that the value is not an empty string. We cannot override this check in our concretion as the method is private.
I will raise a ticket with bulkscan to add a empty string check to this method as well [see here](https://github.com/hmcts/bsp-common-lib/blob/9be0bf74674bde8f43051ee09fc73d67f1130abc/src/main/java/uk/gov/hmcts/reform/bsp/c …
> Convert empty string values to null in OCR case data mapping

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/FinremCaseData.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/RefugeWrapper.java
https://tools.hmcts.net/jira/browse/DFR-3069
Added new respondentInRefuge field.  Within a new RefugeWrapper.  This wrapper will accomodate the applicant and intervener refuge fields at a later point.
Manual CCD tests.  Unit tests.
> DFR-3069: Added new respondentInRefuge field

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/RestService.java
Remove logging of request and response bodies as they can have sensitive data such as auth tokens.
> Remove logging request and response bodies

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/correspondence/CaseDetailsMultiLetterOrEmailAllPartiesCorresponder.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/correspondence/FinremMultiLetterOrEmailAllPartiesCorresponder.java
https://tools.hmcts.net/jira/browse/DFR-3129
Enable printing of documents to be overridden in child classes.
Create protected methods in the abstract class and move current implementation into those methods.
This enables child classes to have different implementations for sending documents to either applicant or respondent.
This requirements is needed for DFR-3129.
> DFR-3129: Enable printing of documents to be overridden

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersMidEventHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/draftorders/upload/suggested/UploadedDraftOrder.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersMidEventHandlerTest.java
See [DFR-3536](https://tools.hmcts.net/jira/browse/DFR-3536)
> DFR-3536 Upload of draft orders additional attachments should be restricted to PDF docs

- build.gradle
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/AmendApplicationContestedControllerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ContestedOrderControllerTest.java
https://tools.hmcts.net/jira/browse/DFR-3626
- Remove multiple occurrences of JSONObject in tests - removing the android-json transitive dependency that comes from jsonassert
- Remove jsonassert dependency as it isn't required
> DFR-3626: Remove multiple occurrences of JSONObject

- build.gradle
Mockito hasn't been updated in ages due to previous team closing the renovate PR.
Bump mockito to 5.15.2.
> Bump mockito to 5.15.2

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/CaseOrchestrationApplication.java
https://tools.hmcts.net/jira/browse/DFR-3659
Prevent logging production data. This will happening due to the presence of a CommonsRequestLoggingFilter bean.
Only enable CommonsRequestLoggingFilter in development.
> DFR-3659: Prevent logging production data 

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/CallbackHandlerLogger.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/casesubmission/CaseSubmissionPbaValidateMidEventHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersAboutToStartHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersAboutToSubmitHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/draftorders/upload/UploadDraftOrdersSubmittedHandler.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/FinremCallbackRequestFactory.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/CallbackHandlerLoggerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/casesubmission/CaseSubmissionPbaValidateMidEventHandlerTest.java
https://tools.hmcts.net/jira/browse/DFR-3667
Add utility class to provide consistent logging of callback requests for handlers. The goal is to make it easier to identify handler execution in AppInsights
Example log message:
`===> Case ID 1739457437734617: Handling CONTESTED About To Start callback for event FR_draftOrders`
> DFR-3667: Add callback handler logger utility

- build.gradle
Bump jose4j to fix [CVE-2023-51775](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-51775)
> Bump jose4j to fix CVE-2023-51775

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/nocworkflows/UpdateRepresentationService.java
Reduce logging level to info instead of error for user error in notice of change so that it does not get reported in alerts channel.
> Reduce logging level for NOC error

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/JacksonConfigurationVerifier.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/ObjectMapperConfiguration.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/FeeLookupController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PBAPaymentController.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ReadyForHearingConsentedAboutToStartHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/AmendGeneralEmailTask.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ReadyForHearingConsentedAboutToStartHandlerTest.java
https://tools.hmcts.net/jira/browse/DFR-3845
- Disable Jackson feature AUTO_CLOSE_JSON_CONTENT due to its potential to cause corruption of data that is sent to CCD.
- Remove instances in controllers where ObjectMapper is not DI
- Refactor some handler code that doesn't use DI
> DFR-3845: Disable Jackson feature AUTO_CLOSE_JSON_CONTENT

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralemail/GeneralEmailAboutToStartHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralemail/GeneralEmailAboutToSubmitHandler.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralemail/GeneralEmailMidHandler.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralemail/GeneralEmailAboutToStartHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralemail/GeneralEmailAboutToSubmitHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/creategeneralemail/GeneralEmailMidHandlerTest.java
Move Create General Email handlers into their own package
Tested event still runs locally.
> DFR-3915: Move Create General Email handlers into their own package

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/notificationrequest/FinremNotificationRequestMapper.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationService.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/notificationrequest/FinremNotificationRequestMapperTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/FinremNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/NotificationServiceTest.java
Refactor building general email notification requests.
- Created a separate method for creating the general email notification request - this is a copy of the existing generic method used. By creating a distinct method for general email this can then be subsequently enhanced without impacting other notification requests.
- Refactor NotificationService send contested/consented email by moving common code into a separate method (sendGeneralEmail)
> DFR-3915: Refactor general email notification requests

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/notification/NotificationRequest.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/domain/EmailToSend.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/service/EmailService.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/service/LocalEmailService.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/domain/EmailToSendTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/domain/NotificationRequestTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/service/EmailServiceTest.java
Add emailReplyToId field that can be used to hold the reply-to UUID for identifying what reply-to email address gov.uk notify should use when sending emails
Note this PR is not populating this field; it is just adding it and will be populated in a later PR.
It will just set the value to null which will not break current email sending functionality. This field is optional:
https://docs.notifications.service.gov.uk/java.html#emailreplytoid-optional
See https://github.com/alphagov/notifications-java-client/blob/e537917e0b22161c52dc6dd36a31951be4b3cd1a/src/main/java/uk/gov/service/notify/NotificationClient.java#L169
Local testing to ensure emails are still sent when emailReplyToId = null
> DFR-3915: Add emailReplyToId field for gov.uk notify requests

- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/config/CourtDetails.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/ConsentedApplicationHelper.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/notificationrequest/AbstractNotificationRequestMapper.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/notificationrequest/NotificationRequestBuilder.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/notificationrequest/NotificationRequestBuilderFactory.java
- src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/notification/NotificationRequest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/CourtDetailsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/notificationrequest/NotificationRequestBuilderFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/notificationrequest/NotificationRequestBuilderTest.java
- src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/notifications/domain/NotificationRequestTest.java
This PR does not change any functionality.
- Add NotificationRequestBuilder that enables NotificationRequest objects to be created using Spring beans.
- The builder needs to be created as a Spring prototype bean so that it can store state whilst the NotificationRequest is being built.
- NotificationRequestBuilderFactory is used to create builder instances.
- Add in fields to CourtDetails and NotificationRequest that will be used in subsequent PR to populate email data
Tested that emails still send
> DFR-3915: Add NotificationRequestBuilder

- src/main/resources/json/court-details.json
Add emailReplyToId config. These are the ids that govuk.notify uses to determine which reply-to email address to use.
The only court that has not been updated is Central Family Court - this is awaiting confirmation from service as to what email address to use.
> DFR-3915: Add emailReplyToId config
